
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  Staff: 'Staff',
  Section: 'Section',
  Table: 'Table',
  Reservation: 'Reservation',
  MenuCategory: 'MenuCategory',
  MenuItem: 'MenuItem',
  Order: 'Order',
  OrderItem: 'OrderItem',
  Payment: 'Payment',
  BuzzerRequest: 'BuzzerRequest',
  Supplier: 'Supplier',
  Purchase: 'Purchase',
  VATRate: 'VATRate',
  TaxPeriod: 'TaxPeriod',
  VATReturn: 'VATReturn',
  AccountingSettings: 'AccountingSettings',
  AuditLog: 'AuditLog'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  role: 'role',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const StaffScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  role: 'role',
  pin: 'pin',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StaffScalarFieldEnum = (typeof StaffScalarFieldEnum)[keyof typeof StaffScalarFieldEnum]


export const SectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  capacity: 'capacity',
  active: 'active'
} as const

export type SectionScalarFieldEnum = (typeof SectionScalarFieldEnum)[keyof typeof SectionScalarFieldEnum]


export const TableScalarFieldEnum = {
  id: 'id',
  number: 'number',
  capacity: 'capacity',
  sectionId: 'sectionId',
  status: 'status',
  currentGuests: 'currentGuests',
  qrCode: 'qrCode',
  assignedWaiterId: 'assignedWaiterId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TableScalarFieldEnum = (typeof TableScalarFieldEnum)[keyof typeof TableScalarFieldEnum]


export const ReservationScalarFieldEnum = {
  id: 'id',
  customerName: 'customerName',
  customerPhone: 'customerPhone',
  customerEmail: 'customerEmail',
  partySize: 'partySize',
  tableId: 'tableId',
  reservationTime: 'reservationTime',
  status: 'status',
  specialRequests: 'specialRequests',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReservationScalarFieldEnum = (typeof ReservationScalarFieldEnum)[keyof typeof ReservationScalarFieldEnum]


export const MenuCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameTr: 'nameTr',
  description: 'description',
  type: 'type',
  displayOrder: 'displayOrder',
  active: 'active'
} as const

export type MenuCategoryScalarFieldEnum = (typeof MenuCategoryScalarFieldEnum)[keyof typeof MenuCategoryScalarFieldEnum]


export const MenuItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameTr: 'nameTr',
  description: 'description',
  descriptionTr: 'descriptionTr',
  categoryId: 'categoryId',
  price: 'price',
  image: 'image',
  available: 'available',
  preparationTime: 'preparationTime',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MenuItemScalarFieldEnum = (typeof MenuItemScalarFieldEnum)[keyof typeof MenuItemScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  tableId: 'tableId',
  staffId: 'staffId',
  status: 'status',
  orderType: 'orderType',
  subtotal: 'subtotal',
  vatRate: 'vatRate',
  vatAmount: 'vatAmount',
  tax: 'tax',
  serviceCharge: 'serviceCharge',
  discount: 'discount',
  total: 'total',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  menuItemId: 'menuItemId',
  quantity: 'quantity',
  price: 'price',
  status: 'status',
  specialInstructions: 'specialInstructions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrderItemScalarFieldEnum = (typeof OrderItemScalarFieldEnum)[keyof typeof OrderItemScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  amount: 'amount',
  method: 'method',
  status: 'status',
  transactionId: 'transactionId',
  createdAt: 'createdAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const BuzzerRequestScalarFieldEnum = {
  id: 'id',
  tableId: 'tableId',
  requestType: 'requestType',
  status: 'status',
  acknowledgedBy: 'acknowledgedBy',
  acknowledgedAt: 'acknowledgedAt',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BuzzerRequestScalarFieldEnum = (typeof BuzzerRequestScalarFieldEnum)[keyof typeof BuzzerRequestScalarFieldEnum]


export const SupplierScalarFieldEnum = {
  id: 'id',
  name: 'name',
  vatNumber: 'vatNumber',
  address: 'address',
  phone: 'phone',
  email: 'email',
  contactName: 'contactName',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SupplierScalarFieldEnum = (typeof SupplierScalarFieldEnum)[keyof typeof SupplierScalarFieldEnum]


export const PurchaseScalarFieldEnum = {
  id: 'id',
  supplierId: 'supplierId',
  invoiceNumber: 'invoiceNumber',
  date: 'date',
  category: 'category',
  description: 'description',
  subtotal: 'subtotal',
  vatRate: 'vatRate',
  vatAmount: 'vatAmount',
  total: 'total',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PurchaseScalarFieldEnum = (typeof PurchaseScalarFieldEnum)[keyof typeof PurchaseScalarFieldEnum]


export const VATRateScalarFieldEnum = {
  id: 'id',
  rate: 'rate',
  name: 'name',
  description: 'description',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VATRateScalarFieldEnum = (typeof VATRateScalarFieldEnum)[keyof typeof VATRateScalarFieldEnum]


export const TaxPeriodScalarFieldEnum = {
  id: 'id',
  startDate: 'startDate',
  endDate: 'endDate',
  quarter: 'quarter',
  year: 'year',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TaxPeriodScalarFieldEnum = (typeof TaxPeriodScalarFieldEnum)[keyof typeof TaxPeriodScalarFieldEnum]


export const VATReturnScalarFieldEnum = {
  id: 'id',
  taxPeriodId: 'taxPeriodId',
  outputVAT: 'outputVAT',
  inputVAT: 'inputVAT',
  vatDue: 'vatDue',
  submittedAt: 'submittedAt',
  submittedBy: 'submittedBy',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VATReturnScalarFieldEnum = (typeof VATReturnScalarFieldEnum)[keyof typeof VATReturnScalarFieldEnum]


export const AccountingSettingsScalarFieldEnum = {
  id: 'id',
  vatRegistrationNumber: 'vatRegistrationNumber',
  companyName: 'companyName',
  companyAddress: 'companyAddress',
  companyPhone: 'companyPhone',
  companyEmail: 'companyEmail',
  accountingYearStart: 'accountingYearStart',
  standardVATRate: 'standardVATRate',
  zeroRatedVATRate: 'zeroRatedVATRate',
  exemptVATRate: 'exemptVATRate',
  serviceChargeRate: 'serviceChargeRate',
  currency: 'currency',
  currencySymbol: 'currencySymbol',
  updatedBy: 'updatedBy',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
} as const

export type AccountingSettingsScalarFieldEnum = (typeof AccountingSettingsScalarFieldEnum)[keyof typeof AccountingSettingsScalarFieldEnum]


export const AuditLogScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  action: 'action',
  userId: 'userId',
  userName: 'userName',
  changes: 'changes',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
} as const

export type AuditLogScalarFieldEnum = (typeof AuditLogScalarFieldEnum)[keyof typeof AuditLogScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

