
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 * 
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }


// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-darwin-arm64.dylib.node")
path.join(process.cwd(), "lib/prisma/libquery_engine-darwin-arm64.dylib.node")

// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-rhel-openssl-3.0.x.so.node")
path.join(process.cwd(), "lib/prisma/libquery_engine-rhel-openssl-3.0.x.so.node")

// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-debian-openssl-3.0.x.so.node")
path.join(process.cwd(), "lib/prisma/libquery_engine-debian-openssl-3.0.x.so.node")

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Staff
 * 
 */
export type Staff = Prisma.StaffModel
/**
 * Model Section
 * 
 */
export type Section = Prisma.SectionModel
/**
 * Model Table
 * 
 */
export type Table = Prisma.TableModel
/**
 * Model Reservation
 * 
 */
export type Reservation = Prisma.ReservationModel
/**
 * Model MenuCategory
 * 
 */
export type MenuCategory = Prisma.MenuCategoryModel
/**
 * Model MenuItem
 * 
 */
export type MenuItem = Prisma.MenuItemModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model BuzzerRequest
 * 
 */
export type BuzzerRequest = Prisma.BuzzerRequestModel
/**
 * Model Supplier
 * 
 */
export type Supplier = Prisma.SupplierModel
/**
 * Model Purchase
 * 
 */
export type Purchase = Prisma.PurchaseModel
/**
 * Model VATRate
 * 
 */
export type VATRate = Prisma.VATRateModel
/**
 * Model TaxPeriod
 * 
 */
export type TaxPeriod = Prisma.TaxPeriodModel
/**
 * Model VATReturn
 * 
 */
export type VATReturn = Prisma.VATReturnModel
/**
 * Model AccountingSettings
 * 
 */
export type AccountingSettings = Prisma.AccountingSettingsModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
