
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccountingSettings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AccountingSettings
 * 
 */
export type AccountingSettingsModel = runtime.Types.Result.DefaultSelection<Prisma.$AccountingSettingsPayload>

export type AggregateAccountingSettings = {
  _count: AccountingSettingsCountAggregateOutputType | null
  _avg: AccountingSettingsAvgAggregateOutputType | null
  _sum: AccountingSettingsSumAggregateOutputType | null
  _min: AccountingSettingsMinAggregateOutputType | null
  _max: AccountingSettingsMaxAggregateOutputType | null
}

export type AccountingSettingsAvgAggregateOutputType = {
  accountingYearStart: number | null
  standardVATRate: number | null
  zeroRatedVATRate: number | null
  exemptVATRate: number | null
  serviceChargeRate: number | null
}

export type AccountingSettingsSumAggregateOutputType = {
  accountingYearStart: number | null
  standardVATRate: number | null
  zeroRatedVATRate: number | null
  exemptVATRate: number | null
  serviceChargeRate: number | null
}

export type AccountingSettingsMinAggregateOutputType = {
  id: string | null
  vatRegistrationNumber: string | null
  companyName: string | null
  companyAddress: string | null
  companyPhone: string | null
  companyEmail: string | null
  accountingYearStart: number | null
  standardVATRate: number | null
  zeroRatedVATRate: number | null
  exemptVATRate: number | null
  serviceChargeRate: number | null
  currency: string | null
  currencySymbol: string | null
  updatedBy: string | null
  updatedAt: Date | null
  createdAt: Date | null
}

export type AccountingSettingsMaxAggregateOutputType = {
  id: string | null
  vatRegistrationNumber: string | null
  companyName: string | null
  companyAddress: string | null
  companyPhone: string | null
  companyEmail: string | null
  accountingYearStart: number | null
  standardVATRate: number | null
  zeroRatedVATRate: number | null
  exemptVATRate: number | null
  serviceChargeRate: number | null
  currency: string | null
  currencySymbol: string | null
  updatedBy: string | null
  updatedAt: Date | null
  createdAt: Date | null
}

export type AccountingSettingsCountAggregateOutputType = {
  id: number
  vatRegistrationNumber: number
  companyName: number
  companyAddress: number
  companyPhone: number
  companyEmail: number
  accountingYearStart: number
  standardVATRate: number
  zeroRatedVATRate: number
  exemptVATRate: number
  serviceChargeRate: number
  currency: number
  currencySymbol: number
  updatedBy: number
  updatedAt: number
  createdAt: number
  _all: number
}


export type AccountingSettingsAvgAggregateInputType = {
  accountingYearStart?: true
  standardVATRate?: true
  zeroRatedVATRate?: true
  exemptVATRate?: true
  serviceChargeRate?: true
}

export type AccountingSettingsSumAggregateInputType = {
  accountingYearStart?: true
  standardVATRate?: true
  zeroRatedVATRate?: true
  exemptVATRate?: true
  serviceChargeRate?: true
}

export type AccountingSettingsMinAggregateInputType = {
  id?: true
  vatRegistrationNumber?: true
  companyName?: true
  companyAddress?: true
  companyPhone?: true
  companyEmail?: true
  accountingYearStart?: true
  standardVATRate?: true
  zeroRatedVATRate?: true
  exemptVATRate?: true
  serviceChargeRate?: true
  currency?: true
  currencySymbol?: true
  updatedBy?: true
  updatedAt?: true
  createdAt?: true
}

export type AccountingSettingsMaxAggregateInputType = {
  id?: true
  vatRegistrationNumber?: true
  companyName?: true
  companyAddress?: true
  companyPhone?: true
  companyEmail?: true
  accountingYearStart?: true
  standardVATRate?: true
  zeroRatedVATRate?: true
  exemptVATRate?: true
  serviceChargeRate?: true
  currency?: true
  currencySymbol?: true
  updatedBy?: true
  updatedAt?: true
  createdAt?: true
}

export type AccountingSettingsCountAggregateInputType = {
  id?: true
  vatRegistrationNumber?: true
  companyName?: true
  companyAddress?: true
  companyPhone?: true
  companyEmail?: true
  accountingYearStart?: true
  standardVATRate?: true
  zeroRatedVATRate?: true
  exemptVATRate?: true
  serviceChargeRate?: true
  currency?: true
  currencySymbol?: true
  updatedBy?: true
  updatedAt?: true
  createdAt?: true
  _all?: true
}

export type AccountingSettingsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountingSettings to aggregate.
   */
  where?: Prisma.AccountingSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountingSettings to fetch.
   */
  orderBy?: Prisma.AccountingSettingsOrderByWithRelationInput | Prisma.AccountingSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccountingSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountingSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountingSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccountingSettings
  **/
  _count?: true | AccountingSettingsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AccountingSettingsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AccountingSettingsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccountingSettingsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccountingSettingsMaxAggregateInputType
}

export type GetAccountingSettingsAggregateType<T extends AccountingSettingsAggregateArgs> = {
      [P in keyof T & keyof AggregateAccountingSettings]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccountingSettings[P]>
    : Prisma.GetScalarType<T[P], AggregateAccountingSettings[P]>
}




export type AccountingSettingsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountingSettingsWhereInput
  orderBy?: Prisma.AccountingSettingsOrderByWithAggregationInput | Prisma.AccountingSettingsOrderByWithAggregationInput[]
  by: Prisma.AccountingSettingsScalarFieldEnum[] | Prisma.AccountingSettingsScalarFieldEnum
  having?: Prisma.AccountingSettingsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccountingSettingsCountAggregateInputType | true
  _avg?: AccountingSettingsAvgAggregateInputType
  _sum?: AccountingSettingsSumAggregateInputType
  _min?: AccountingSettingsMinAggregateInputType
  _max?: AccountingSettingsMaxAggregateInputType
}

export type AccountingSettingsGroupByOutputType = {
  id: string
  vatRegistrationNumber: string | null
  companyName: string | null
  companyAddress: string | null
  companyPhone: string | null
  companyEmail: string | null
  accountingYearStart: number
  standardVATRate: number
  zeroRatedVATRate: number
  exemptVATRate: number
  serviceChargeRate: number
  currency: string
  currencySymbol: string
  updatedBy: string | null
  updatedAt: Date
  createdAt: Date
  _count: AccountingSettingsCountAggregateOutputType | null
  _avg: AccountingSettingsAvgAggregateOutputType | null
  _sum: AccountingSettingsSumAggregateOutputType | null
  _min: AccountingSettingsMinAggregateOutputType | null
  _max: AccountingSettingsMaxAggregateOutputType | null
}

type GetAccountingSettingsGroupByPayload<T extends AccountingSettingsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccountingSettingsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccountingSettingsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccountingSettingsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccountingSettingsGroupByOutputType[P]>
      }
    >
  >



export type AccountingSettingsWhereInput = {
  AND?: Prisma.AccountingSettingsWhereInput | Prisma.AccountingSettingsWhereInput[]
  OR?: Prisma.AccountingSettingsWhereInput[]
  NOT?: Prisma.AccountingSettingsWhereInput | Prisma.AccountingSettingsWhereInput[]
  id?: Prisma.StringFilter<"AccountingSettings"> | string
  vatRegistrationNumber?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  companyName?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  companyAddress?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  companyPhone?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  companyEmail?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  accountingYearStart?: Prisma.IntFilter<"AccountingSettings"> | number
  standardVATRate?: Prisma.FloatFilter<"AccountingSettings"> | number
  zeroRatedVATRate?: Prisma.FloatFilter<"AccountingSettings"> | number
  exemptVATRate?: Prisma.FloatFilter<"AccountingSettings"> | number
  serviceChargeRate?: Prisma.FloatFilter<"AccountingSettings"> | number
  currency?: Prisma.StringFilter<"AccountingSettings"> | string
  currencySymbol?: Prisma.StringFilter<"AccountingSettings"> | string
  updatedBy?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"AccountingSettings"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"AccountingSettings"> | Date | string
}

export type AccountingSettingsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  vatRegistrationNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  companyName?: Prisma.SortOrderInput | Prisma.SortOrder
  companyAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  companyPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  companyEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  accountingYearStart?: Prisma.SortOrder
  standardVATRate?: Prisma.SortOrder
  zeroRatedVATRate?: Prisma.SortOrder
  exemptVATRate?: Prisma.SortOrder
  serviceChargeRate?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  currencySymbol?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AccountingSettingsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AccountingSettingsWhereInput | Prisma.AccountingSettingsWhereInput[]
  OR?: Prisma.AccountingSettingsWhereInput[]
  NOT?: Prisma.AccountingSettingsWhereInput | Prisma.AccountingSettingsWhereInput[]
  vatRegistrationNumber?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  companyName?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  companyAddress?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  companyPhone?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  companyEmail?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  accountingYearStart?: Prisma.IntFilter<"AccountingSettings"> | number
  standardVATRate?: Prisma.FloatFilter<"AccountingSettings"> | number
  zeroRatedVATRate?: Prisma.FloatFilter<"AccountingSettings"> | number
  exemptVATRate?: Prisma.FloatFilter<"AccountingSettings"> | number
  serviceChargeRate?: Prisma.FloatFilter<"AccountingSettings"> | number
  currency?: Prisma.StringFilter<"AccountingSettings"> | string
  currencySymbol?: Prisma.StringFilter<"AccountingSettings"> | string
  updatedBy?: Prisma.StringNullableFilter<"AccountingSettings"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"AccountingSettings"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"AccountingSettings"> | Date | string
}, "id" | "id">

export type AccountingSettingsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  vatRegistrationNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  companyName?: Prisma.SortOrderInput | Prisma.SortOrder
  companyAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  companyPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  companyEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  accountingYearStart?: Prisma.SortOrder
  standardVATRate?: Prisma.SortOrder
  zeroRatedVATRate?: Prisma.SortOrder
  exemptVATRate?: Prisma.SortOrder
  serviceChargeRate?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  currencySymbol?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AccountingSettingsCountOrderByAggregateInput
  _avg?: Prisma.AccountingSettingsAvgOrderByAggregateInput
  _max?: Prisma.AccountingSettingsMaxOrderByAggregateInput
  _min?: Prisma.AccountingSettingsMinOrderByAggregateInput
  _sum?: Prisma.AccountingSettingsSumOrderByAggregateInput
}

export type AccountingSettingsScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccountingSettingsScalarWhereWithAggregatesInput | Prisma.AccountingSettingsScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccountingSettingsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccountingSettingsScalarWhereWithAggregatesInput | Prisma.AccountingSettingsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AccountingSettings"> | string
  vatRegistrationNumber?: Prisma.StringNullableWithAggregatesFilter<"AccountingSettings"> | string | null
  companyName?: Prisma.StringNullableWithAggregatesFilter<"AccountingSettings"> | string | null
  companyAddress?: Prisma.StringNullableWithAggregatesFilter<"AccountingSettings"> | string | null
  companyPhone?: Prisma.StringNullableWithAggregatesFilter<"AccountingSettings"> | string | null
  companyEmail?: Prisma.StringNullableWithAggregatesFilter<"AccountingSettings"> | string | null
  accountingYearStart?: Prisma.IntWithAggregatesFilter<"AccountingSettings"> | number
  standardVATRate?: Prisma.FloatWithAggregatesFilter<"AccountingSettings"> | number
  zeroRatedVATRate?: Prisma.FloatWithAggregatesFilter<"AccountingSettings"> | number
  exemptVATRate?: Prisma.FloatWithAggregatesFilter<"AccountingSettings"> | number
  serviceChargeRate?: Prisma.FloatWithAggregatesFilter<"AccountingSettings"> | number
  currency?: Prisma.StringWithAggregatesFilter<"AccountingSettings"> | string
  currencySymbol?: Prisma.StringWithAggregatesFilter<"AccountingSettings"> | string
  updatedBy?: Prisma.StringNullableWithAggregatesFilter<"AccountingSettings"> | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AccountingSettings"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AccountingSettings"> | Date | string
}

export type AccountingSettingsCreateInput = {
  id?: string
  vatRegistrationNumber?: string | null
  companyName?: string | null
  companyAddress?: string | null
  companyPhone?: string | null
  companyEmail?: string | null
  accountingYearStart?: number
  standardVATRate?: number
  zeroRatedVATRate?: number
  exemptVATRate?: number
  serviceChargeRate?: number
  currency?: string
  currencySymbol?: string
  updatedBy?: string | null
  updatedAt?: Date | string
  createdAt?: Date | string
}

export type AccountingSettingsUncheckedCreateInput = {
  id?: string
  vatRegistrationNumber?: string | null
  companyName?: string | null
  companyAddress?: string | null
  companyPhone?: string | null
  companyEmail?: string | null
  accountingYearStart?: number
  standardVATRate?: number
  zeroRatedVATRate?: number
  exemptVATRate?: number
  serviceChargeRate?: number
  currency?: string
  currencySymbol?: string
  updatedBy?: string | null
  updatedAt?: Date | string
  createdAt?: Date | string
}

export type AccountingSettingsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vatRegistrationNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accountingYearStart?: Prisma.IntFieldUpdateOperationsInput | number
  standardVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  zeroRatedVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  exemptVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  serviceChargeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  currencySymbol?: Prisma.StringFieldUpdateOperationsInput | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountingSettingsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vatRegistrationNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accountingYearStart?: Prisma.IntFieldUpdateOperationsInput | number
  standardVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  zeroRatedVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  exemptVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  serviceChargeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  currencySymbol?: Prisma.StringFieldUpdateOperationsInput | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountingSettingsCreateManyInput = {
  id?: string
  vatRegistrationNumber?: string | null
  companyName?: string | null
  companyAddress?: string | null
  companyPhone?: string | null
  companyEmail?: string | null
  accountingYearStart?: number
  standardVATRate?: number
  zeroRatedVATRate?: number
  exemptVATRate?: number
  serviceChargeRate?: number
  currency?: string
  currencySymbol?: string
  updatedBy?: string | null
  updatedAt?: Date | string
  createdAt?: Date | string
}

export type AccountingSettingsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vatRegistrationNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accountingYearStart?: Prisma.IntFieldUpdateOperationsInput | number
  standardVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  zeroRatedVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  exemptVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  serviceChargeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  currencySymbol?: Prisma.StringFieldUpdateOperationsInput | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountingSettingsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vatRegistrationNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accountingYearStart?: Prisma.IntFieldUpdateOperationsInput | number
  standardVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  zeroRatedVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  exemptVATRate?: Prisma.FloatFieldUpdateOperationsInput | number
  serviceChargeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  currencySymbol?: Prisma.StringFieldUpdateOperationsInput | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountingSettingsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vatRegistrationNumber?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  companyAddress?: Prisma.SortOrder
  companyPhone?: Prisma.SortOrder
  companyEmail?: Prisma.SortOrder
  accountingYearStart?: Prisma.SortOrder
  standardVATRate?: Prisma.SortOrder
  zeroRatedVATRate?: Prisma.SortOrder
  exemptVATRate?: Prisma.SortOrder
  serviceChargeRate?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  currencySymbol?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AccountingSettingsAvgOrderByAggregateInput = {
  accountingYearStart?: Prisma.SortOrder
  standardVATRate?: Prisma.SortOrder
  zeroRatedVATRate?: Prisma.SortOrder
  exemptVATRate?: Prisma.SortOrder
  serviceChargeRate?: Prisma.SortOrder
}

export type AccountingSettingsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vatRegistrationNumber?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  companyAddress?: Prisma.SortOrder
  companyPhone?: Prisma.SortOrder
  companyEmail?: Prisma.SortOrder
  accountingYearStart?: Prisma.SortOrder
  standardVATRate?: Prisma.SortOrder
  zeroRatedVATRate?: Prisma.SortOrder
  exemptVATRate?: Prisma.SortOrder
  serviceChargeRate?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  currencySymbol?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AccountingSettingsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vatRegistrationNumber?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  companyAddress?: Prisma.SortOrder
  companyPhone?: Prisma.SortOrder
  companyEmail?: Prisma.SortOrder
  accountingYearStart?: Prisma.SortOrder
  standardVATRate?: Prisma.SortOrder
  zeroRatedVATRate?: Prisma.SortOrder
  exemptVATRate?: Prisma.SortOrder
  serviceChargeRate?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  currencySymbol?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AccountingSettingsSumOrderByAggregateInput = {
  accountingYearStart?: Prisma.SortOrder
  standardVATRate?: Prisma.SortOrder
  zeroRatedVATRate?: Prisma.SortOrder
  exemptVATRate?: Prisma.SortOrder
  serviceChargeRate?: Prisma.SortOrder
}



export type AccountingSettingsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vatRegistrationNumber?: boolean
  companyName?: boolean
  companyAddress?: boolean
  companyPhone?: boolean
  companyEmail?: boolean
  accountingYearStart?: boolean
  standardVATRate?: boolean
  zeroRatedVATRate?: boolean
  exemptVATRate?: boolean
  serviceChargeRate?: boolean
  currency?: boolean
  currencySymbol?: boolean
  updatedBy?: boolean
  updatedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["accountingSettings"]>

export type AccountingSettingsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vatRegistrationNumber?: boolean
  companyName?: boolean
  companyAddress?: boolean
  companyPhone?: boolean
  companyEmail?: boolean
  accountingYearStart?: boolean
  standardVATRate?: boolean
  zeroRatedVATRate?: boolean
  exemptVATRate?: boolean
  serviceChargeRate?: boolean
  currency?: boolean
  currencySymbol?: boolean
  updatedBy?: boolean
  updatedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["accountingSettings"]>

export type AccountingSettingsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vatRegistrationNumber?: boolean
  companyName?: boolean
  companyAddress?: boolean
  companyPhone?: boolean
  companyEmail?: boolean
  accountingYearStart?: boolean
  standardVATRate?: boolean
  zeroRatedVATRate?: boolean
  exemptVATRate?: boolean
  serviceChargeRate?: boolean
  currency?: boolean
  currencySymbol?: boolean
  updatedBy?: boolean
  updatedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["accountingSettings"]>

export type AccountingSettingsSelectScalar = {
  id?: boolean
  vatRegistrationNumber?: boolean
  companyName?: boolean
  companyAddress?: boolean
  companyPhone?: boolean
  companyEmail?: boolean
  accountingYearStart?: boolean
  standardVATRate?: boolean
  zeroRatedVATRate?: boolean
  exemptVATRate?: boolean
  serviceChargeRate?: boolean
  currency?: boolean
  currencySymbol?: boolean
  updatedBy?: boolean
  updatedAt?: boolean
  createdAt?: boolean
}

export type AccountingSettingsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "vatRegistrationNumber" | "companyName" | "companyAddress" | "companyPhone" | "companyEmail" | "accountingYearStart" | "standardVATRate" | "zeroRatedVATRate" | "exemptVATRate" | "serviceChargeRate" | "currency" | "currencySymbol" | "updatedBy" | "updatedAt" | "createdAt", ExtArgs["result"]["accountingSettings"]>

export type $AccountingSettingsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccountingSettings"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    vatRegistrationNumber: string | null
    companyName: string | null
    companyAddress: string | null
    companyPhone: string | null
    companyEmail: string | null
    accountingYearStart: number
    standardVATRate: number
    zeroRatedVATRate: number
    exemptVATRate: number
    serviceChargeRate: number
    currency: string
    currencySymbol: string
    updatedBy: string | null
    updatedAt: Date
    createdAt: Date
  }, ExtArgs["result"]["accountingSettings"]>
  composites: {}
}

export type AccountingSettingsGetPayload<S extends boolean | null | undefined | AccountingSettingsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload, S>

export type AccountingSettingsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccountingSettingsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccountingSettingsCountAggregateInputType | true
  }

export interface AccountingSettingsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccountingSettings'], meta: { name: 'AccountingSettings' } }
  /**
   * Find zero or one AccountingSettings that matches the filter.
   * @param {AccountingSettingsFindUniqueArgs} args - Arguments to find a AccountingSettings
   * @example
   * // Get one AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccountingSettingsFindUniqueArgs>(args: Prisma.SelectSubset<T, AccountingSettingsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccountingSettingsClient<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccountingSettings that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccountingSettingsFindUniqueOrThrowArgs} args - Arguments to find a AccountingSettings
   * @example
   * // Get one AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccountingSettingsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccountingSettingsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountingSettingsClient<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountingSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingSettingsFindFirstArgs} args - Arguments to find a AccountingSettings
   * @example
   * // Get one AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccountingSettingsFindFirstArgs>(args?: Prisma.SelectSubset<T, AccountingSettingsFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccountingSettingsClient<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountingSettings that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingSettingsFindFirstOrThrowArgs} args - Arguments to find a AccountingSettings
   * @example
   * // Get one AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccountingSettingsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccountingSettingsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountingSettingsClient<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccountingSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingSettingsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.findMany()
   * 
   * // Get first 10 AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accountingSettingsWithIdOnly = await prisma.accountingSettings.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccountingSettingsFindManyArgs>(args?: Prisma.SelectSubset<T, AccountingSettingsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccountingSettings.
   * @param {AccountingSettingsCreateArgs} args - Arguments to create a AccountingSettings.
   * @example
   * // Create one AccountingSettings
   * const AccountingSettings = await prisma.accountingSettings.create({
   *   data: {
   *     // ... data to create a AccountingSettings
   *   }
   * })
   * 
   */
  create<T extends AccountingSettingsCreateArgs>(args: Prisma.SelectSubset<T, AccountingSettingsCreateArgs<ExtArgs>>): Prisma.Prisma__AccountingSettingsClient<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccountingSettings.
   * @param {AccountingSettingsCreateManyArgs} args - Arguments to create many AccountingSettings.
   * @example
   * // Create many AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccountingSettingsCreateManyArgs>(args?: Prisma.SelectSubset<T, AccountingSettingsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccountingSettings and returns the data saved in the database.
   * @param {AccountingSettingsCreateManyAndReturnArgs} args - Arguments to create many AccountingSettings.
   * @example
   * // Create many AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccountingSettings and only return the `id`
   * const accountingSettingsWithIdOnly = await prisma.accountingSettings.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccountingSettingsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccountingSettingsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccountingSettings.
   * @param {AccountingSettingsDeleteArgs} args - Arguments to delete one AccountingSettings.
   * @example
   * // Delete one AccountingSettings
   * const AccountingSettings = await prisma.accountingSettings.delete({
   *   where: {
   *     // ... filter to delete one AccountingSettings
   *   }
   * })
   * 
   */
  delete<T extends AccountingSettingsDeleteArgs>(args: Prisma.SelectSubset<T, AccountingSettingsDeleteArgs<ExtArgs>>): Prisma.Prisma__AccountingSettingsClient<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccountingSettings.
   * @param {AccountingSettingsUpdateArgs} args - Arguments to update one AccountingSettings.
   * @example
   * // Update one AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccountingSettingsUpdateArgs>(args: Prisma.SelectSubset<T, AccountingSettingsUpdateArgs<ExtArgs>>): Prisma.Prisma__AccountingSettingsClient<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccountingSettings.
   * @param {AccountingSettingsDeleteManyArgs} args - Arguments to filter AccountingSettings to delete.
   * @example
   * // Delete a few AccountingSettings
   * const { count } = await prisma.accountingSettings.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccountingSettingsDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccountingSettingsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountingSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingSettingsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccountingSettingsUpdateManyArgs>(args: Prisma.SelectSubset<T, AccountingSettingsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountingSettings and returns the data updated in the database.
   * @param {AccountingSettingsUpdateManyAndReturnArgs} args - Arguments to update many AccountingSettings.
   * @example
   * // Update many AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccountingSettings and only return the `id`
   * const accountingSettingsWithIdOnly = await prisma.accountingSettings.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccountingSettingsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccountingSettingsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccountingSettings.
   * @param {AccountingSettingsUpsertArgs} args - Arguments to update or create a AccountingSettings.
   * @example
   * // Update or create a AccountingSettings
   * const accountingSettings = await prisma.accountingSettings.upsert({
   *   create: {
   *     // ... data to create a AccountingSettings
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccountingSettings we want to update
   *   }
   * })
   */
  upsert<T extends AccountingSettingsUpsertArgs>(args: Prisma.SelectSubset<T, AccountingSettingsUpsertArgs<ExtArgs>>): Prisma.Prisma__AccountingSettingsClient<runtime.Types.Result.GetResult<Prisma.$AccountingSettingsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccountingSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingSettingsCountArgs} args - Arguments to filter AccountingSettings to count.
   * @example
   * // Count the number of AccountingSettings
   * const count = await prisma.accountingSettings.count({
   *   where: {
   *     // ... the filter for the AccountingSettings we want to count
   *   }
   * })
  **/
  count<T extends AccountingSettingsCountArgs>(
    args?: Prisma.Subset<T, AccountingSettingsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccountingSettingsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccountingSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingSettingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccountingSettingsAggregateArgs>(args: Prisma.Subset<T, AccountingSettingsAggregateArgs>): Prisma.PrismaPromise<GetAccountingSettingsAggregateType<T>>

  /**
   * Group by AccountingSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingSettingsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccountingSettingsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccountingSettingsGroupByArgs['orderBy'] }
      : { orderBy?: AccountingSettingsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccountingSettingsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccountingSettingsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccountingSettings model
 */
readonly fields: AccountingSettingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccountingSettings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccountingSettingsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccountingSettings model
 */
export interface AccountingSettingsFieldRefs {
  readonly id: Prisma.FieldRef<"AccountingSettings", 'String'>
  readonly vatRegistrationNumber: Prisma.FieldRef<"AccountingSettings", 'String'>
  readonly companyName: Prisma.FieldRef<"AccountingSettings", 'String'>
  readonly companyAddress: Prisma.FieldRef<"AccountingSettings", 'String'>
  readonly companyPhone: Prisma.FieldRef<"AccountingSettings", 'String'>
  readonly companyEmail: Prisma.FieldRef<"AccountingSettings", 'String'>
  readonly accountingYearStart: Prisma.FieldRef<"AccountingSettings", 'Int'>
  readonly standardVATRate: Prisma.FieldRef<"AccountingSettings", 'Float'>
  readonly zeroRatedVATRate: Prisma.FieldRef<"AccountingSettings", 'Float'>
  readonly exemptVATRate: Prisma.FieldRef<"AccountingSettings", 'Float'>
  readonly serviceChargeRate: Prisma.FieldRef<"AccountingSettings", 'Float'>
  readonly currency: Prisma.FieldRef<"AccountingSettings", 'String'>
  readonly currencySymbol: Prisma.FieldRef<"AccountingSettings", 'String'>
  readonly updatedBy: Prisma.FieldRef<"AccountingSettings", 'String'>
  readonly updatedAt: Prisma.FieldRef<"AccountingSettings", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"AccountingSettings", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AccountingSettings findUnique
 */
export type AccountingSettingsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * Filter, which AccountingSettings to fetch.
   */
  where: Prisma.AccountingSettingsWhereUniqueInput
}

/**
 * AccountingSettings findUniqueOrThrow
 */
export type AccountingSettingsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * Filter, which AccountingSettings to fetch.
   */
  where: Prisma.AccountingSettingsWhereUniqueInput
}

/**
 * AccountingSettings findFirst
 */
export type AccountingSettingsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * Filter, which AccountingSettings to fetch.
   */
  where?: Prisma.AccountingSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountingSettings to fetch.
   */
  orderBy?: Prisma.AccountingSettingsOrderByWithRelationInput | Prisma.AccountingSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountingSettings.
   */
  cursor?: Prisma.AccountingSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountingSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountingSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountingSettings.
   */
  distinct?: Prisma.AccountingSettingsScalarFieldEnum | Prisma.AccountingSettingsScalarFieldEnum[]
}

/**
 * AccountingSettings findFirstOrThrow
 */
export type AccountingSettingsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * Filter, which AccountingSettings to fetch.
   */
  where?: Prisma.AccountingSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountingSettings to fetch.
   */
  orderBy?: Prisma.AccountingSettingsOrderByWithRelationInput | Prisma.AccountingSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountingSettings.
   */
  cursor?: Prisma.AccountingSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountingSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountingSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountingSettings.
   */
  distinct?: Prisma.AccountingSettingsScalarFieldEnum | Prisma.AccountingSettingsScalarFieldEnum[]
}

/**
 * AccountingSettings findMany
 */
export type AccountingSettingsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * Filter, which AccountingSettings to fetch.
   */
  where?: Prisma.AccountingSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountingSettings to fetch.
   */
  orderBy?: Prisma.AccountingSettingsOrderByWithRelationInput | Prisma.AccountingSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccountingSettings.
   */
  cursor?: Prisma.AccountingSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountingSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountingSettings.
   */
  skip?: number
  distinct?: Prisma.AccountingSettingsScalarFieldEnum | Prisma.AccountingSettingsScalarFieldEnum[]
}

/**
 * AccountingSettings create
 */
export type AccountingSettingsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * The data needed to create a AccountingSettings.
   */
  data: Prisma.XOR<Prisma.AccountingSettingsCreateInput, Prisma.AccountingSettingsUncheckedCreateInput>
}

/**
 * AccountingSettings createMany
 */
export type AccountingSettingsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccountingSettings.
   */
  data: Prisma.AccountingSettingsCreateManyInput | Prisma.AccountingSettingsCreateManyInput[]
}

/**
 * AccountingSettings createManyAndReturn
 */
export type AccountingSettingsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * The data used to create many AccountingSettings.
   */
  data: Prisma.AccountingSettingsCreateManyInput | Prisma.AccountingSettingsCreateManyInput[]
}

/**
 * AccountingSettings update
 */
export type AccountingSettingsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * The data needed to update a AccountingSettings.
   */
  data: Prisma.XOR<Prisma.AccountingSettingsUpdateInput, Prisma.AccountingSettingsUncheckedUpdateInput>
  /**
   * Choose, which AccountingSettings to update.
   */
  where: Prisma.AccountingSettingsWhereUniqueInput
}

/**
 * AccountingSettings updateMany
 */
export type AccountingSettingsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccountingSettings.
   */
  data: Prisma.XOR<Prisma.AccountingSettingsUpdateManyMutationInput, Prisma.AccountingSettingsUncheckedUpdateManyInput>
  /**
   * Filter which AccountingSettings to update
   */
  where?: Prisma.AccountingSettingsWhereInput
  /**
   * Limit how many AccountingSettings to update.
   */
  limit?: number
}

/**
 * AccountingSettings updateManyAndReturn
 */
export type AccountingSettingsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * The data used to update AccountingSettings.
   */
  data: Prisma.XOR<Prisma.AccountingSettingsUpdateManyMutationInput, Prisma.AccountingSettingsUncheckedUpdateManyInput>
  /**
   * Filter which AccountingSettings to update
   */
  where?: Prisma.AccountingSettingsWhereInput
  /**
   * Limit how many AccountingSettings to update.
   */
  limit?: number
}

/**
 * AccountingSettings upsert
 */
export type AccountingSettingsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * The filter to search for the AccountingSettings to update in case it exists.
   */
  where: Prisma.AccountingSettingsWhereUniqueInput
  /**
   * In case the AccountingSettings found by the `where` argument doesn't exist, create a new AccountingSettings with this data.
   */
  create: Prisma.XOR<Prisma.AccountingSettingsCreateInput, Prisma.AccountingSettingsUncheckedCreateInput>
  /**
   * In case the AccountingSettings was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccountingSettingsUpdateInput, Prisma.AccountingSettingsUncheckedUpdateInput>
}

/**
 * AccountingSettings delete
 */
export type AccountingSettingsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
  /**
   * Filter which AccountingSettings to delete.
   */
  where: Prisma.AccountingSettingsWhereUniqueInput
}

/**
 * AccountingSettings deleteMany
 */
export type AccountingSettingsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountingSettings to delete
   */
  where?: Prisma.AccountingSettingsWhereInput
  /**
   * Limit how many AccountingSettings to delete.
   */
  limit?: number
}

/**
 * AccountingSettings without action
 */
export type AccountingSettingsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingSettings
   */
  select?: Prisma.AccountingSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountingSettings
   */
  omit?: Prisma.AccountingSettingsOmit<ExtArgs> | null
}
