
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BuzzerRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BuzzerRequest
 * 
 */
export type BuzzerRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$BuzzerRequestPayload>

export type AggregateBuzzerRequest = {
  _count: BuzzerRequestCountAggregateOutputType | null
  _min: BuzzerRequestMinAggregateOutputType | null
  _max: BuzzerRequestMaxAggregateOutputType | null
}

export type BuzzerRequestMinAggregateOutputType = {
  id: string | null
  tableId: string | null
  requestType: string | null
  status: string | null
  acknowledgedBy: string | null
  acknowledgedAt: Date | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BuzzerRequestMaxAggregateOutputType = {
  id: string | null
  tableId: string | null
  requestType: string | null
  status: string | null
  acknowledgedBy: string | null
  acknowledgedAt: Date | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BuzzerRequestCountAggregateOutputType = {
  id: number
  tableId: number
  requestType: number
  status: number
  acknowledgedBy: number
  acknowledgedAt: number
  completedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BuzzerRequestMinAggregateInputType = {
  id?: true
  tableId?: true
  requestType?: true
  status?: true
  acknowledgedBy?: true
  acknowledgedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type BuzzerRequestMaxAggregateInputType = {
  id?: true
  tableId?: true
  requestType?: true
  status?: true
  acknowledgedBy?: true
  acknowledgedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type BuzzerRequestCountAggregateInputType = {
  id?: true
  tableId?: true
  requestType?: true
  status?: true
  acknowledgedBy?: true
  acknowledgedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BuzzerRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BuzzerRequest to aggregate.
   */
  where?: Prisma.BuzzerRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuzzerRequests to fetch.
   */
  orderBy?: Prisma.BuzzerRequestOrderByWithRelationInput | Prisma.BuzzerRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BuzzerRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuzzerRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuzzerRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BuzzerRequests
  **/
  _count?: true | BuzzerRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BuzzerRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BuzzerRequestMaxAggregateInputType
}

export type GetBuzzerRequestAggregateType<T extends BuzzerRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateBuzzerRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBuzzerRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateBuzzerRequest[P]>
}




export type BuzzerRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BuzzerRequestWhereInput
  orderBy?: Prisma.BuzzerRequestOrderByWithAggregationInput | Prisma.BuzzerRequestOrderByWithAggregationInput[]
  by: Prisma.BuzzerRequestScalarFieldEnum[] | Prisma.BuzzerRequestScalarFieldEnum
  having?: Prisma.BuzzerRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BuzzerRequestCountAggregateInputType | true
  _min?: BuzzerRequestMinAggregateInputType
  _max?: BuzzerRequestMaxAggregateInputType
}

export type BuzzerRequestGroupByOutputType = {
  id: string
  tableId: string
  requestType: string
  status: string
  acknowledgedBy: string | null
  acknowledgedAt: Date | null
  completedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: BuzzerRequestCountAggregateOutputType | null
  _min: BuzzerRequestMinAggregateOutputType | null
  _max: BuzzerRequestMaxAggregateOutputType | null
}

type GetBuzzerRequestGroupByPayload<T extends BuzzerRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BuzzerRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BuzzerRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BuzzerRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BuzzerRequestGroupByOutputType[P]>
      }
    >
  >



export type BuzzerRequestWhereInput = {
  AND?: Prisma.BuzzerRequestWhereInput | Prisma.BuzzerRequestWhereInput[]
  OR?: Prisma.BuzzerRequestWhereInput[]
  NOT?: Prisma.BuzzerRequestWhereInput | Prisma.BuzzerRequestWhereInput[]
  id?: Prisma.StringFilter<"BuzzerRequest"> | string
  tableId?: Prisma.StringFilter<"BuzzerRequest"> | string
  requestType?: Prisma.StringFilter<"BuzzerRequest"> | string
  status?: Prisma.StringFilter<"BuzzerRequest"> | string
  acknowledgedBy?: Prisma.StringNullableFilter<"BuzzerRequest"> | string | null
  acknowledgedAt?: Prisma.DateTimeNullableFilter<"BuzzerRequest"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"BuzzerRequest"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BuzzerRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BuzzerRequest"> | Date | string
  table?: Prisma.XOR<Prisma.TableScalarRelationFilter, Prisma.TableWhereInput>
}

export type BuzzerRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tableId?: Prisma.SortOrder
  requestType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  acknowledgedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  acknowledgedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  table?: Prisma.TableOrderByWithRelationInput
}

export type BuzzerRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BuzzerRequestWhereInput | Prisma.BuzzerRequestWhereInput[]
  OR?: Prisma.BuzzerRequestWhereInput[]
  NOT?: Prisma.BuzzerRequestWhereInput | Prisma.BuzzerRequestWhereInput[]
  tableId?: Prisma.StringFilter<"BuzzerRequest"> | string
  requestType?: Prisma.StringFilter<"BuzzerRequest"> | string
  status?: Prisma.StringFilter<"BuzzerRequest"> | string
  acknowledgedBy?: Prisma.StringNullableFilter<"BuzzerRequest"> | string | null
  acknowledgedAt?: Prisma.DateTimeNullableFilter<"BuzzerRequest"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"BuzzerRequest"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BuzzerRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BuzzerRequest"> | Date | string
  table?: Prisma.XOR<Prisma.TableScalarRelationFilter, Prisma.TableWhereInput>
}, "id">

export type BuzzerRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tableId?: Prisma.SortOrder
  requestType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  acknowledgedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  acknowledgedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BuzzerRequestCountOrderByAggregateInput
  _max?: Prisma.BuzzerRequestMaxOrderByAggregateInput
  _min?: Prisma.BuzzerRequestMinOrderByAggregateInput
}

export type BuzzerRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.BuzzerRequestScalarWhereWithAggregatesInput | Prisma.BuzzerRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.BuzzerRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BuzzerRequestScalarWhereWithAggregatesInput | Prisma.BuzzerRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BuzzerRequest"> | string
  tableId?: Prisma.StringWithAggregatesFilter<"BuzzerRequest"> | string
  requestType?: Prisma.StringWithAggregatesFilter<"BuzzerRequest"> | string
  status?: Prisma.StringWithAggregatesFilter<"BuzzerRequest"> | string
  acknowledgedBy?: Prisma.StringNullableWithAggregatesFilter<"BuzzerRequest"> | string | null
  acknowledgedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"BuzzerRequest"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"BuzzerRequest"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BuzzerRequest"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BuzzerRequest"> | Date | string
}

export type BuzzerRequestCreateInput = {
  id?: string
  requestType: string
  status?: string
  acknowledgedBy?: string | null
  acknowledgedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  table: Prisma.TableCreateNestedOneWithoutBuzzerRequestsInput
}

export type BuzzerRequestUncheckedCreateInput = {
  id?: string
  tableId: string
  requestType: string
  status?: string
  acknowledgedBy?: string | null
  acknowledgedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BuzzerRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  acknowledgedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  acknowledgedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  table?: Prisma.TableUpdateOneRequiredWithoutBuzzerRequestsNestedInput
}

export type BuzzerRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tableId?: Prisma.StringFieldUpdateOperationsInput | string
  requestType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  acknowledgedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  acknowledgedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BuzzerRequestCreateManyInput = {
  id?: string
  tableId: string
  requestType: string
  status?: string
  acknowledgedBy?: string | null
  acknowledgedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BuzzerRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  acknowledgedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  acknowledgedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BuzzerRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tableId?: Prisma.StringFieldUpdateOperationsInput | string
  requestType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  acknowledgedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  acknowledgedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BuzzerRequestListRelationFilter = {
  every?: Prisma.BuzzerRequestWhereInput
  some?: Prisma.BuzzerRequestWhereInput
  none?: Prisma.BuzzerRequestWhereInput
}

export type BuzzerRequestOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BuzzerRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tableId?: Prisma.SortOrder
  requestType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  acknowledgedBy?: Prisma.SortOrder
  acknowledgedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BuzzerRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tableId?: Prisma.SortOrder
  requestType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  acknowledgedBy?: Prisma.SortOrder
  acknowledgedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BuzzerRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tableId?: Prisma.SortOrder
  requestType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  acknowledgedBy?: Prisma.SortOrder
  acknowledgedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BuzzerRequestCreateNestedManyWithoutTableInput = {
  create?: Prisma.XOR<Prisma.BuzzerRequestCreateWithoutTableInput, Prisma.BuzzerRequestUncheckedCreateWithoutTableInput> | Prisma.BuzzerRequestCreateWithoutTableInput[] | Prisma.BuzzerRequestUncheckedCreateWithoutTableInput[]
  connectOrCreate?: Prisma.BuzzerRequestCreateOrConnectWithoutTableInput | Prisma.BuzzerRequestCreateOrConnectWithoutTableInput[]
  createMany?: Prisma.BuzzerRequestCreateManyTableInputEnvelope
  connect?: Prisma.BuzzerRequestWhereUniqueInput | Prisma.BuzzerRequestWhereUniqueInput[]
}

export type BuzzerRequestUncheckedCreateNestedManyWithoutTableInput = {
  create?: Prisma.XOR<Prisma.BuzzerRequestCreateWithoutTableInput, Prisma.BuzzerRequestUncheckedCreateWithoutTableInput> | Prisma.BuzzerRequestCreateWithoutTableInput[] | Prisma.BuzzerRequestUncheckedCreateWithoutTableInput[]
  connectOrCreate?: Prisma.BuzzerRequestCreateOrConnectWithoutTableInput | Prisma.BuzzerRequestCreateOrConnectWithoutTableInput[]
  createMany?: Prisma.BuzzerRequestCreateManyTableInputEnvelope
  connect?: Prisma.BuzzerRequestWhereUniqueInput | Prisma.BuzzerRequestWhereUniqueInput[]
}

export type BuzzerRequestUpdateManyWithoutTableNestedInput = {
  create?: Prisma.XOR<Prisma.BuzzerRequestCreateWithoutTableInput, Prisma.BuzzerRequestUncheckedCreateWithoutTableInput> | Prisma.BuzzerRequestCreateWithoutTableInput[] | Prisma.BuzzerRequestUncheckedCreateWithoutTableInput[]
  connectOrCreate?: Prisma.BuzzerRequestCreateOrConnectWithoutTableInput | Prisma.BuzzerRequestCreateOrConnectWithoutTableInput[]
  upsert?: Prisma.BuzzerRequestUpsertWithWhereUniqueWithoutTableInput | Prisma.BuzzerRequestUpsertWithWhereUniqueWithoutTableInput[]
  createMany?: Prisma.BuzzerRequestCreateManyTableInputEnvelope
  set?: Prisma.BuzzerRequestWhereUniqueInput | Prisma.BuzzerRequestWhereUniqueInput[]
  disconnect?: Prisma.BuzzerRequestWhereUniqueInput | Prisma.BuzzerRequestWhereUniqueInput[]
  delete?: Prisma.BuzzerRequestWhereUniqueInput | Prisma.BuzzerRequestWhereUniqueInput[]
  connect?: Prisma.BuzzerRequestWhereUniqueInput | Prisma.BuzzerRequestWhereUniqueInput[]
  update?: Prisma.BuzzerRequestUpdateWithWhereUniqueWithoutTableInput | Prisma.BuzzerRequestUpdateWithWhereUniqueWithoutTableInput[]
  updateMany?: Prisma.BuzzerRequestUpdateManyWithWhereWithoutTableInput | Prisma.BuzzerRequestUpdateManyWithWhereWithoutTableInput[]
  deleteMany?: Prisma.BuzzerRequestScalarWhereInput | Prisma.BuzzerRequestScalarWhereInput[]
}

export type BuzzerRequestUncheckedUpdateManyWithoutTableNestedInput = {
  create?: Prisma.XOR<Prisma.BuzzerRequestCreateWithoutTableInput, Prisma.BuzzerRequestUncheckedCreateWithoutTableInput> | Prisma.BuzzerRequestCreateWithoutTableInput[] | Prisma.BuzzerRequestUncheckedCreateWithoutTableInput[]
  connectOrCreate?: Prisma.BuzzerRequestCreateOrConnectWithoutTableInput | Prisma.BuzzerRequestCreateOrConnectWithoutTableInput[]
  upsert?: Prisma.BuzzerRequestUpsertWithWhereUniqueWithoutTableInput | Prisma.BuzzerRequestUpsertWithWhereUniqueWithoutTableInput[]
  createMany?: Prisma.BuzzerRequestCreateManyTableInputEnvelope
  set?: Prisma.BuzzerRequestWhereUniqueInput | Prisma.BuzzerRequestWhereUniqueInput[]
  disconnect?: Prisma.BuzzerRequestWhereUniqueInput | Prisma.BuzzerRequestWhereUniqueInput[]
  delete?: Prisma.BuzzerRequestWhereUniqueInput | Prisma.BuzzerRequestWhereUniqueInput[]
  connect?: Prisma.BuzzerRequestWhereUniqueInput | Prisma.BuzzerRequestWhereUniqueInput[]
  update?: Prisma.BuzzerRequestUpdateWithWhereUniqueWithoutTableInput | Prisma.BuzzerRequestUpdateWithWhereUniqueWithoutTableInput[]
  updateMany?: Prisma.BuzzerRequestUpdateManyWithWhereWithoutTableInput | Prisma.BuzzerRequestUpdateManyWithWhereWithoutTableInput[]
  deleteMany?: Prisma.BuzzerRequestScalarWhereInput | Prisma.BuzzerRequestScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type BuzzerRequestCreateWithoutTableInput = {
  id?: string
  requestType: string
  status?: string
  acknowledgedBy?: string | null
  acknowledgedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BuzzerRequestUncheckedCreateWithoutTableInput = {
  id?: string
  requestType: string
  status?: string
  acknowledgedBy?: string | null
  acknowledgedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BuzzerRequestCreateOrConnectWithoutTableInput = {
  where: Prisma.BuzzerRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.BuzzerRequestCreateWithoutTableInput, Prisma.BuzzerRequestUncheckedCreateWithoutTableInput>
}

export type BuzzerRequestCreateManyTableInputEnvelope = {
  data: Prisma.BuzzerRequestCreateManyTableInput | Prisma.BuzzerRequestCreateManyTableInput[]
  skipDuplicates?: boolean
}

export type BuzzerRequestUpsertWithWhereUniqueWithoutTableInput = {
  where: Prisma.BuzzerRequestWhereUniqueInput
  update: Prisma.XOR<Prisma.BuzzerRequestUpdateWithoutTableInput, Prisma.BuzzerRequestUncheckedUpdateWithoutTableInput>
  create: Prisma.XOR<Prisma.BuzzerRequestCreateWithoutTableInput, Prisma.BuzzerRequestUncheckedCreateWithoutTableInput>
}

export type BuzzerRequestUpdateWithWhereUniqueWithoutTableInput = {
  where: Prisma.BuzzerRequestWhereUniqueInput
  data: Prisma.XOR<Prisma.BuzzerRequestUpdateWithoutTableInput, Prisma.BuzzerRequestUncheckedUpdateWithoutTableInput>
}

export type BuzzerRequestUpdateManyWithWhereWithoutTableInput = {
  where: Prisma.BuzzerRequestScalarWhereInput
  data: Prisma.XOR<Prisma.BuzzerRequestUpdateManyMutationInput, Prisma.BuzzerRequestUncheckedUpdateManyWithoutTableInput>
}

export type BuzzerRequestScalarWhereInput = {
  AND?: Prisma.BuzzerRequestScalarWhereInput | Prisma.BuzzerRequestScalarWhereInput[]
  OR?: Prisma.BuzzerRequestScalarWhereInput[]
  NOT?: Prisma.BuzzerRequestScalarWhereInput | Prisma.BuzzerRequestScalarWhereInput[]
  id?: Prisma.StringFilter<"BuzzerRequest"> | string
  tableId?: Prisma.StringFilter<"BuzzerRequest"> | string
  requestType?: Prisma.StringFilter<"BuzzerRequest"> | string
  status?: Prisma.StringFilter<"BuzzerRequest"> | string
  acknowledgedBy?: Prisma.StringNullableFilter<"BuzzerRequest"> | string | null
  acknowledgedAt?: Prisma.DateTimeNullableFilter<"BuzzerRequest"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"BuzzerRequest"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BuzzerRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BuzzerRequest"> | Date | string
}

export type BuzzerRequestCreateManyTableInput = {
  id?: string
  requestType: string
  status?: string
  acknowledgedBy?: string | null
  acknowledgedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BuzzerRequestUpdateWithoutTableInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  acknowledgedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  acknowledgedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BuzzerRequestUncheckedUpdateWithoutTableInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  acknowledgedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  acknowledgedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BuzzerRequestUncheckedUpdateManyWithoutTableInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  acknowledgedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  acknowledgedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type BuzzerRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tableId?: boolean
  requestType?: boolean
  status?: boolean
  acknowledgedBy?: boolean
  acknowledgedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  table?: boolean | Prisma.TableDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buzzerRequest"]>

export type BuzzerRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tableId?: boolean
  requestType?: boolean
  status?: boolean
  acknowledgedBy?: boolean
  acknowledgedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  table?: boolean | Prisma.TableDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buzzerRequest"]>

export type BuzzerRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tableId?: boolean
  requestType?: boolean
  status?: boolean
  acknowledgedBy?: boolean
  acknowledgedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  table?: boolean | Prisma.TableDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buzzerRequest"]>

export type BuzzerRequestSelectScalar = {
  id?: boolean
  tableId?: boolean
  requestType?: boolean
  status?: boolean
  acknowledgedBy?: boolean
  acknowledgedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BuzzerRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tableId" | "requestType" | "status" | "acknowledgedBy" | "acknowledgedAt" | "completedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["buzzerRequest"]>
export type BuzzerRequestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  table?: boolean | Prisma.TableDefaultArgs<ExtArgs>
}
export type BuzzerRequestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  table?: boolean | Prisma.TableDefaultArgs<ExtArgs>
}
export type BuzzerRequestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  table?: boolean | Prisma.TableDefaultArgs<ExtArgs>
}

export type $BuzzerRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BuzzerRequest"
  objects: {
    table: Prisma.$TablePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tableId: string
    requestType: string
    status: string
    acknowledgedBy: string | null
    acknowledgedAt: Date | null
    completedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["buzzerRequest"]>
  composites: {}
}

export type BuzzerRequestGetPayload<S extends boolean | null | undefined | BuzzerRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload, S>

export type BuzzerRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BuzzerRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BuzzerRequestCountAggregateInputType | true
  }

export interface BuzzerRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BuzzerRequest'], meta: { name: 'BuzzerRequest' } }
  /**
   * Find zero or one BuzzerRequest that matches the filter.
   * @param {BuzzerRequestFindUniqueArgs} args - Arguments to find a BuzzerRequest
   * @example
   * // Get one BuzzerRequest
   * const buzzerRequest = await prisma.buzzerRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BuzzerRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, BuzzerRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BuzzerRequestClient<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BuzzerRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BuzzerRequestFindUniqueOrThrowArgs} args - Arguments to find a BuzzerRequest
   * @example
   * // Get one BuzzerRequest
   * const buzzerRequest = await prisma.buzzerRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BuzzerRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BuzzerRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BuzzerRequestClient<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BuzzerRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuzzerRequestFindFirstArgs} args - Arguments to find a BuzzerRequest
   * @example
   * // Get one BuzzerRequest
   * const buzzerRequest = await prisma.buzzerRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BuzzerRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, BuzzerRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__BuzzerRequestClient<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BuzzerRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuzzerRequestFindFirstOrThrowArgs} args - Arguments to find a BuzzerRequest
   * @example
   * // Get one BuzzerRequest
   * const buzzerRequest = await prisma.buzzerRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BuzzerRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BuzzerRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BuzzerRequestClient<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BuzzerRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuzzerRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BuzzerRequests
   * const buzzerRequests = await prisma.buzzerRequest.findMany()
   * 
   * // Get first 10 BuzzerRequests
   * const buzzerRequests = await prisma.buzzerRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const buzzerRequestWithIdOnly = await prisma.buzzerRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BuzzerRequestFindManyArgs>(args?: Prisma.SelectSubset<T, BuzzerRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BuzzerRequest.
   * @param {BuzzerRequestCreateArgs} args - Arguments to create a BuzzerRequest.
   * @example
   * // Create one BuzzerRequest
   * const BuzzerRequest = await prisma.buzzerRequest.create({
   *   data: {
   *     // ... data to create a BuzzerRequest
   *   }
   * })
   * 
   */
  create<T extends BuzzerRequestCreateArgs>(args: Prisma.SelectSubset<T, BuzzerRequestCreateArgs<ExtArgs>>): Prisma.Prisma__BuzzerRequestClient<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BuzzerRequests.
   * @param {BuzzerRequestCreateManyArgs} args - Arguments to create many BuzzerRequests.
   * @example
   * // Create many BuzzerRequests
   * const buzzerRequest = await prisma.buzzerRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BuzzerRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, BuzzerRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BuzzerRequests and returns the data saved in the database.
   * @param {BuzzerRequestCreateManyAndReturnArgs} args - Arguments to create many BuzzerRequests.
   * @example
   * // Create many BuzzerRequests
   * const buzzerRequest = await prisma.buzzerRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BuzzerRequests and only return the `id`
   * const buzzerRequestWithIdOnly = await prisma.buzzerRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BuzzerRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BuzzerRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BuzzerRequest.
   * @param {BuzzerRequestDeleteArgs} args - Arguments to delete one BuzzerRequest.
   * @example
   * // Delete one BuzzerRequest
   * const BuzzerRequest = await prisma.buzzerRequest.delete({
   *   where: {
   *     // ... filter to delete one BuzzerRequest
   *   }
   * })
   * 
   */
  delete<T extends BuzzerRequestDeleteArgs>(args: Prisma.SelectSubset<T, BuzzerRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__BuzzerRequestClient<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BuzzerRequest.
   * @param {BuzzerRequestUpdateArgs} args - Arguments to update one BuzzerRequest.
   * @example
   * // Update one BuzzerRequest
   * const buzzerRequest = await prisma.buzzerRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BuzzerRequestUpdateArgs>(args: Prisma.SelectSubset<T, BuzzerRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__BuzzerRequestClient<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BuzzerRequests.
   * @param {BuzzerRequestDeleteManyArgs} args - Arguments to filter BuzzerRequests to delete.
   * @example
   * // Delete a few BuzzerRequests
   * const { count } = await prisma.buzzerRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BuzzerRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, BuzzerRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BuzzerRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuzzerRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BuzzerRequests
   * const buzzerRequest = await prisma.buzzerRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BuzzerRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, BuzzerRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BuzzerRequests and returns the data updated in the database.
   * @param {BuzzerRequestUpdateManyAndReturnArgs} args - Arguments to update many BuzzerRequests.
   * @example
   * // Update many BuzzerRequests
   * const buzzerRequest = await prisma.buzzerRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BuzzerRequests and only return the `id`
   * const buzzerRequestWithIdOnly = await prisma.buzzerRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BuzzerRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BuzzerRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BuzzerRequest.
   * @param {BuzzerRequestUpsertArgs} args - Arguments to update or create a BuzzerRequest.
   * @example
   * // Update or create a BuzzerRequest
   * const buzzerRequest = await prisma.buzzerRequest.upsert({
   *   create: {
   *     // ... data to create a BuzzerRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BuzzerRequest we want to update
   *   }
   * })
   */
  upsert<T extends BuzzerRequestUpsertArgs>(args: Prisma.SelectSubset<T, BuzzerRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__BuzzerRequestClient<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BuzzerRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuzzerRequestCountArgs} args - Arguments to filter BuzzerRequests to count.
   * @example
   * // Count the number of BuzzerRequests
   * const count = await prisma.buzzerRequest.count({
   *   where: {
   *     // ... the filter for the BuzzerRequests we want to count
   *   }
   * })
  **/
  count<T extends BuzzerRequestCountArgs>(
    args?: Prisma.Subset<T, BuzzerRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BuzzerRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BuzzerRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuzzerRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BuzzerRequestAggregateArgs>(args: Prisma.Subset<T, BuzzerRequestAggregateArgs>): Prisma.PrismaPromise<GetBuzzerRequestAggregateType<T>>

  /**
   * Group by BuzzerRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuzzerRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BuzzerRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BuzzerRequestGroupByArgs['orderBy'] }
      : { orderBy?: BuzzerRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BuzzerRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBuzzerRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BuzzerRequest model
 */
readonly fields: BuzzerRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BuzzerRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BuzzerRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  table<T extends Prisma.TableDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TableDefaultArgs<ExtArgs>>): Prisma.Prisma__TableClient<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BuzzerRequest model
 */
export interface BuzzerRequestFieldRefs {
  readonly id: Prisma.FieldRef<"BuzzerRequest", 'String'>
  readonly tableId: Prisma.FieldRef<"BuzzerRequest", 'String'>
  readonly requestType: Prisma.FieldRef<"BuzzerRequest", 'String'>
  readonly status: Prisma.FieldRef<"BuzzerRequest", 'String'>
  readonly acknowledgedBy: Prisma.FieldRef<"BuzzerRequest", 'String'>
  readonly acknowledgedAt: Prisma.FieldRef<"BuzzerRequest", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"BuzzerRequest", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"BuzzerRequest", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BuzzerRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BuzzerRequest findUnique
 */
export type BuzzerRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
  /**
   * Filter, which BuzzerRequest to fetch.
   */
  where: Prisma.BuzzerRequestWhereUniqueInput
}

/**
 * BuzzerRequest findUniqueOrThrow
 */
export type BuzzerRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
  /**
   * Filter, which BuzzerRequest to fetch.
   */
  where: Prisma.BuzzerRequestWhereUniqueInput
}

/**
 * BuzzerRequest findFirst
 */
export type BuzzerRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
  /**
   * Filter, which BuzzerRequest to fetch.
   */
  where?: Prisma.BuzzerRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuzzerRequests to fetch.
   */
  orderBy?: Prisma.BuzzerRequestOrderByWithRelationInput | Prisma.BuzzerRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BuzzerRequests.
   */
  cursor?: Prisma.BuzzerRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuzzerRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuzzerRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BuzzerRequests.
   */
  distinct?: Prisma.BuzzerRequestScalarFieldEnum | Prisma.BuzzerRequestScalarFieldEnum[]
}

/**
 * BuzzerRequest findFirstOrThrow
 */
export type BuzzerRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
  /**
   * Filter, which BuzzerRequest to fetch.
   */
  where?: Prisma.BuzzerRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuzzerRequests to fetch.
   */
  orderBy?: Prisma.BuzzerRequestOrderByWithRelationInput | Prisma.BuzzerRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BuzzerRequests.
   */
  cursor?: Prisma.BuzzerRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuzzerRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuzzerRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BuzzerRequests.
   */
  distinct?: Prisma.BuzzerRequestScalarFieldEnum | Prisma.BuzzerRequestScalarFieldEnum[]
}

/**
 * BuzzerRequest findMany
 */
export type BuzzerRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
  /**
   * Filter, which BuzzerRequests to fetch.
   */
  where?: Prisma.BuzzerRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuzzerRequests to fetch.
   */
  orderBy?: Prisma.BuzzerRequestOrderByWithRelationInput | Prisma.BuzzerRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BuzzerRequests.
   */
  cursor?: Prisma.BuzzerRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuzzerRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuzzerRequests.
   */
  skip?: number
  distinct?: Prisma.BuzzerRequestScalarFieldEnum | Prisma.BuzzerRequestScalarFieldEnum[]
}

/**
 * BuzzerRequest create
 */
export type BuzzerRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
  /**
   * The data needed to create a BuzzerRequest.
   */
  data: Prisma.XOR<Prisma.BuzzerRequestCreateInput, Prisma.BuzzerRequestUncheckedCreateInput>
}

/**
 * BuzzerRequest createMany
 */
export type BuzzerRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BuzzerRequests.
   */
  data: Prisma.BuzzerRequestCreateManyInput | Prisma.BuzzerRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BuzzerRequest createManyAndReturn
 */
export type BuzzerRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * The data used to create many BuzzerRequests.
   */
  data: Prisma.BuzzerRequestCreateManyInput | Prisma.BuzzerRequestCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BuzzerRequest update
 */
export type BuzzerRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
  /**
   * The data needed to update a BuzzerRequest.
   */
  data: Prisma.XOR<Prisma.BuzzerRequestUpdateInput, Prisma.BuzzerRequestUncheckedUpdateInput>
  /**
   * Choose, which BuzzerRequest to update.
   */
  where: Prisma.BuzzerRequestWhereUniqueInput
}

/**
 * BuzzerRequest updateMany
 */
export type BuzzerRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BuzzerRequests.
   */
  data: Prisma.XOR<Prisma.BuzzerRequestUpdateManyMutationInput, Prisma.BuzzerRequestUncheckedUpdateManyInput>
  /**
   * Filter which BuzzerRequests to update
   */
  where?: Prisma.BuzzerRequestWhereInput
  /**
   * Limit how many BuzzerRequests to update.
   */
  limit?: number
}

/**
 * BuzzerRequest updateManyAndReturn
 */
export type BuzzerRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * The data used to update BuzzerRequests.
   */
  data: Prisma.XOR<Prisma.BuzzerRequestUpdateManyMutationInput, Prisma.BuzzerRequestUncheckedUpdateManyInput>
  /**
   * Filter which BuzzerRequests to update
   */
  where?: Prisma.BuzzerRequestWhereInput
  /**
   * Limit how many BuzzerRequests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BuzzerRequest upsert
 */
export type BuzzerRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
  /**
   * The filter to search for the BuzzerRequest to update in case it exists.
   */
  where: Prisma.BuzzerRequestWhereUniqueInput
  /**
   * In case the BuzzerRequest found by the `where` argument doesn't exist, create a new BuzzerRequest with this data.
   */
  create: Prisma.XOR<Prisma.BuzzerRequestCreateInput, Prisma.BuzzerRequestUncheckedCreateInput>
  /**
   * In case the BuzzerRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BuzzerRequestUpdateInput, Prisma.BuzzerRequestUncheckedUpdateInput>
}

/**
 * BuzzerRequest delete
 */
export type BuzzerRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
  /**
   * Filter which BuzzerRequest to delete.
   */
  where: Prisma.BuzzerRequestWhereUniqueInput
}

/**
 * BuzzerRequest deleteMany
 */
export type BuzzerRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BuzzerRequests to delete
   */
  where?: Prisma.BuzzerRequestWhereInput
  /**
   * Limit how many BuzzerRequests to delete.
   */
  limit?: number
}

/**
 * BuzzerRequest without action
 */
export type BuzzerRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
}
