
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Table` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Table
 * 
 */
export type TableModel = runtime.Types.Result.DefaultSelection<Prisma.$TablePayload>

export type AggregateTable = {
  _count: TableCountAggregateOutputType | null
  _avg: TableAvgAggregateOutputType | null
  _sum: TableSumAggregateOutputType | null
  _min: TableMinAggregateOutputType | null
  _max: TableMaxAggregateOutputType | null
}

export type TableAvgAggregateOutputType = {
  number: number | null
  capacity: number | null
  currentGuests: number | null
}

export type TableSumAggregateOutputType = {
  number: number | null
  capacity: number | null
  currentGuests: number | null
}

export type TableMinAggregateOutputType = {
  id: string | null
  number: number | null
  capacity: number | null
  sectionId: string | null
  status: string | null
  currentGuests: number | null
  qrCode: string | null
  assignedWaiterId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TableMaxAggregateOutputType = {
  id: string | null
  number: number | null
  capacity: number | null
  sectionId: string | null
  status: string | null
  currentGuests: number | null
  qrCode: string | null
  assignedWaiterId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TableCountAggregateOutputType = {
  id: number
  number: number
  capacity: number
  sectionId: number
  status: number
  currentGuests: number
  qrCode: number
  assignedWaiterId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TableAvgAggregateInputType = {
  number?: true
  capacity?: true
  currentGuests?: true
}

export type TableSumAggregateInputType = {
  number?: true
  capacity?: true
  currentGuests?: true
}

export type TableMinAggregateInputType = {
  id?: true
  number?: true
  capacity?: true
  sectionId?: true
  status?: true
  currentGuests?: true
  qrCode?: true
  assignedWaiterId?: true
  createdAt?: true
  updatedAt?: true
}

export type TableMaxAggregateInputType = {
  id?: true
  number?: true
  capacity?: true
  sectionId?: true
  status?: true
  currentGuests?: true
  qrCode?: true
  assignedWaiterId?: true
  createdAt?: true
  updatedAt?: true
}

export type TableCountAggregateInputType = {
  id?: true
  number?: true
  capacity?: true
  sectionId?: true
  status?: true
  currentGuests?: true
  qrCode?: true
  assignedWaiterId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TableAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Table to aggregate.
   */
  where?: Prisma.TableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tables to fetch.
   */
  orderBy?: Prisma.TableOrderByWithRelationInput | Prisma.TableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tables
  **/
  _count?: true | TableCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TableAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TableSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TableMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TableMaxAggregateInputType
}

export type GetTableAggregateType<T extends TableAggregateArgs> = {
      [P in keyof T & keyof AggregateTable]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTable[P]>
    : Prisma.GetScalarType<T[P], AggregateTable[P]>
}




export type TableGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TableWhereInput
  orderBy?: Prisma.TableOrderByWithAggregationInput | Prisma.TableOrderByWithAggregationInput[]
  by: Prisma.TableScalarFieldEnum[] | Prisma.TableScalarFieldEnum
  having?: Prisma.TableScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TableCountAggregateInputType | true
  _avg?: TableAvgAggregateInputType
  _sum?: TableSumAggregateInputType
  _min?: TableMinAggregateInputType
  _max?: TableMaxAggregateInputType
}

export type TableGroupByOutputType = {
  id: string
  number: number
  capacity: number
  sectionId: string
  status: string
  currentGuests: number
  qrCode: string | null
  assignedWaiterId: string | null
  createdAt: Date
  updatedAt: Date
  _count: TableCountAggregateOutputType | null
  _avg: TableAvgAggregateOutputType | null
  _sum: TableSumAggregateOutputType | null
  _min: TableMinAggregateOutputType | null
  _max: TableMaxAggregateOutputType | null
}

type GetTableGroupByPayload<T extends TableGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TableGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TableGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TableGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TableGroupByOutputType[P]>
      }
    >
  >



export type TableWhereInput = {
  AND?: Prisma.TableWhereInput | Prisma.TableWhereInput[]
  OR?: Prisma.TableWhereInput[]
  NOT?: Prisma.TableWhereInput | Prisma.TableWhereInput[]
  id?: Prisma.StringFilter<"Table"> | string
  number?: Prisma.IntFilter<"Table"> | number
  capacity?: Prisma.IntFilter<"Table"> | number
  sectionId?: Prisma.StringFilter<"Table"> | string
  status?: Prisma.StringFilter<"Table"> | string
  currentGuests?: Prisma.IntFilter<"Table"> | number
  qrCode?: Prisma.StringNullableFilter<"Table"> | string | null
  assignedWaiterId?: Prisma.StringNullableFilter<"Table"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Table"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Table"> | Date | string
  section?: Prisma.XOR<Prisma.SectionScalarRelationFilter, Prisma.SectionWhereInput>
  reservations?: Prisma.ReservationListRelationFilter
  orders?: Prisma.OrderListRelationFilter
  assignedWaiter?: Prisma.XOR<Prisma.StaffNullableScalarRelationFilter, Prisma.StaffWhereInput> | null
  buzzerRequests?: Prisma.BuzzerRequestListRelationFilter
}

export type TableOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  currentGuests?: Prisma.SortOrder
  qrCode?: Prisma.SortOrderInput | Prisma.SortOrder
  assignedWaiterId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  section?: Prisma.SectionOrderByWithRelationInput
  reservations?: Prisma.ReservationOrderByRelationAggregateInput
  orders?: Prisma.OrderOrderByRelationAggregateInput
  assignedWaiter?: Prisma.StaffOrderByWithRelationInput
  buzzerRequests?: Prisma.BuzzerRequestOrderByRelationAggregateInput
}

export type TableWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  number?: number
  qrCode?: string
  AND?: Prisma.TableWhereInput | Prisma.TableWhereInput[]
  OR?: Prisma.TableWhereInput[]
  NOT?: Prisma.TableWhereInput | Prisma.TableWhereInput[]
  capacity?: Prisma.IntFilter<"Table"> | number
  sectionId?: Prisma.StringFilter<"Table"> | string
  status?: Prisma.StringFilter<"Table"> | string
  currentGuests?: Prisma.IntFilter<"Table"> | number
  assignedWaiterId?: Prisma.StringNullableFilter<"Table"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Table"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Table"> | Date | string
  section?: Prisma.XOR<Prisma.SectionScalarRelationFilter, Prisma.SectionWhereInput>
  reservations?: Prisma.ReservationListRelationFilter
  orders?: Prisma.OrderListRelationFilter
  assignedWaiter?: Prisma.XOR<Prisma.StaffNullableScalarRelationFilter, Prisma.StaffWhereInput> | null
  buzzerRequests?: Prisma.BuzzerRequestListRelationFilter
}, "id" | "number" | "qrCode">

export type TableOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  currentGuests?: Prisma.SortOrder
  qrCode?: Prisma.SortOrderInput | Prisma.SortOrder
  assignedWaiterId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TableCountOrderByAggregateInput
  _avg?: Prisma.TableAvgOrderByAggregateInput
  _max?: Prisma.TableMaxOrderByAggregateInput
  _min?: Prisma.TableMinOrderByAggregateInput
  _sum?: Prisma.TableSumOrderByAggregateInput
}

export type TableScalarWhereWithAggregatesInput = {
  AND?: Prisma.TableScalarWhereWithAggregatesInput | Prisma.TableScalarWhereWithAggregatesInput[]
  OR?: Prisma.TableScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TableScalarWhereWithAggregatesInput | Prisma.TableScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Table"> | string
  number?: Prisma.IntWithAggregatesFilter<"Table"> | number
  capacity?: Prisma.IntWithAggregatesFilter<"Table"> | number
  sectionId?: Prisma.StringWithAggregatesFilter<"Table"> | string
  status?: Prisma.StringWithAggregatesFilter<"Table"> | string
  currentGuests?: Prisma.IntWithAggregatesFilter<"Table"> | number
  qrCode?: Prisma.StringNullableWithAggregatesFilter<"Table"> | string | null
  assignedWaiterId?: Prisma.StringNullableWithAggregatesFilter<"Table"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Table"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Table"> | Date | string
}

export type TableCreateInput = {
  id?: string
  number: number
  capacity: number
  status?: string
  currentGuests?: number
  qrCode?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  section: Prisma.SectionCreateNestedOneWithoutTablesInput
  reservations?: Prisma.ReservationCreateNestedManyWithoutTableInput
  orders?: Prisma.OrderCreateNestedManyWithoutTableInput
  assignedWaiter?: Prisma.StaffCreateNestedOneWithoutAssignedTablesInput
  buzzerRequests?: Prisma.BuzzerRequestCreateNestedManyWithoutTableInput
}

export type TableUncheckedCreateInput = {
  id?: string
  number: number
  capacity: number
  sectionId: string
  status?: string
  currentGuests?: number
  qrCode?: string | null
  assignedWaiterId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutTableInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutTableInput
  buzzerRequests?: Prisma.BuzzerRequestUncheckedCreateNestedManyWithoutTableInput
}

export type TableUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  section?: Prisma.SectionUpdateOneRequiredWithoutTablesNestedInput
  reservations?: Prisma.ReservationUpdateManyWithoutTableNestedInput
  orders?: Prisma.OrderUpdateManyWithoutTableNestedInput
  assignedWaiter?: Prisma.StaffUpdateOneWithoutAssignedTablesNestedInput
  buzzerRequests?: Prisma.BuzzerRequestUpdateManyWithoutTableNestedInput
}

export type TableUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedWaiterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutTableNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutTableNestedInput
  buzzerRequests?: Prisma.BuzzerRequestUncheckedUpdateManyWithoutTableNestedInput
}

export type TableCreateManyInput = {
  id?: string
  number: number
  capacity: number
  sectionId: string
  status?: string
  currentGuests?: number
  qrCode?: string | null
  assignedWaiterId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TableUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TableUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedWaiterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TableListRelationFilter = {
  every?: Prisma.TableWhereInput
  some?: Prisma.TableWhereInput
  none?: Prisma.TableWhereInput
}

export type TableOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TableCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  currentGuests?: Prisma.SortOrder
  qrCode?: Prisma.SortOrder
  assignedWaiterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TableAvgOrderByAggregateInput = {
  number?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  currentGuests?: Prisma.SortOrder
}

export type TableMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  currentGuests?: Prisma.SortOrder
  qrCode?: Prisma.SortOrder
  assignedWaiterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TableMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  sectionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  currentGuests?: Prisma.SortOrder
  qrCode?: Prisma.SortOrder
  assignedWaiterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TableSumOrderByAggregateInput = {
  number?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  currentGuests?: Prisma.SortOrder
}

export type TableNullableScalarRelationFilter = {
  is?: Prisma.TableWhereInput | null
  isNot?: Prisma.TableWhereInput | null
}

export type TableScalarRelationFilter = {
  is?: Prisma.TableWhereInput
  isNot?: Prisma.TableWhereInput
}

export type TableCreateNestedManyWithoutAssignedWaiterInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutAssignedWaiterInput, Prisma.TableUncheckedCreateWithoutAssignedWaiterInput> | Prisma.TableCreateWithoutAssignedWaiterInput[] | Prisma.TableUncheckedCreateWithoutAssignedWaiterInput[]
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutAssignedWaiterInput | Prisma.TableCreateOrConnectWithoutAssignedWaiterInput[]
  createMany?: Prisma.TableCreateManyAssignedWaiterInputEnvelope
  connect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
}

export type TableUncheckedCreateNestedManyWithoutAssignedWaiterInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutAssignedWaiterInput, Prisma.TableUncheckedCreateWithoutAssignedWaiterInput> | Prisma.TableCreateWithoutAssignedWaiterInput[] | Prisma.TableUncheckedCreateWithoutAssignedWaiterInput[]
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutAssignedWaiterInput | Prisma.TableCreateOrConnectWithoutAssignedWaiterInput[]
  createMany?: Prisma.TableCreateManyAssignedWaiterInputEnvelope
  connect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
}

export type TableUpdateManyWithoutAssignedWaiterNestedInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutAssignedWaiterInput, Prisma.TableUncheckedCreateWithoutAssignedWaiterInput> | Prisma.TableCreateWithoutAssignedWaiterInput[] | Prisma.TableUncheckedCreateWithoutAssignedWaiterInput[]
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutAssignedWaiterInput | Prisma.TableCreateOrConnectWithoutAssignedWaiterInput[]
  upsert?: Prisma.TableUpsertWithWhereUniqueWithoutAssignedWaiterInput | Prisma.TableUpsertWithWhereUniqueWithoutAssignedWaiterInput[]
  createMany?: Prisma.TableCreateManyAssignedWaiterInputEnvelope
  set?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  disconnect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  delete?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  connect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  update?: Prisma.TableUpdateWithWhereUniqueWithoutAssignedWaiterInput | Prisma.TableUpdateWithWhereUniqueWithoutAssignedWaiterInput[]
  updateMany?: Prisma.TableUpdateManyWithWhereWithoutAssignedWaiterInput | Prisma.TableUpdateManyWithWhereWithoutAssignedWaiterInput[]
  deleteMany?: Prisma.TableScalarWhereInput | Prisma.TableScalarWhereInput[]
}

export type TableUncheckedUpdateManyWithoutAssignedWaiterNestedInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutAssignedWaiterInput, Prisma.TableUncheckedCreateWithoutAssignedWaiterInput> | Prisma.TableCreateWithoutAssignedWaiterInput[] | Prisma.TableUncheckedCreateWithoutAssignedWaiterInput[]
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutAssignedWaiterInput | Prisma.TableCreateOrConnectWithoutAssignedWaiterInput[]
  upsert?: Prisma.TableUpsertWithWhereUniqueWithoutAssignedWaiterInput | Prisma.TableUpsertWithWhereUniqueWithoutAssignedWaiterInput[]
  createMany?: Prisma.TableCreateManyAssignedWaiterInputEnvelope
  set?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  disconnect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  delete?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  connect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  update?: Prisma.TableUpdateWithWhereUniqueWithoutAssignedWaiterInput | Prisma.TableUpdateWithWhereUniqueWithoutAssignedWaiterInput[]
  updateMany?: Prisma.TableUpdateManyWithWhereWithoutAssignedWaiterInput | Prisma.TableUpdateManyWithWhereWithoutAssignedWaiterInput[]
  deleteMany?: Prisma.TableScalarWhereInput | Prisma.TableScalarWhereInput[]
}

export type TableCreateNestedManyWithoutSectionInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutSectionInput, Prisma.TableUncheckedCreateWithoutSectionInput> | Prisma.TableCreateWithoutSectionInput[] | Prisma.TableUncheckedCreateWithoutSectionInput[]
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutSectionInput | Prisma.TableCreateOrConnectWithoutSectionInput[]
  createMany?: Prisma.TableCreateManySectionInputEnvelope
  connect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
}

export type TableUncheckedCreateNestedManyWithoutSectionInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutSectionInput, Prisma.TableUncheckedCreateWithoutSectionInput> | Prisma.TableCreateWithoutSectionInput[] | Prisma.TableUncheckedCreateWithoutSectionInput[]
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutSectionInput | Prisma.TableCreateOrConnectWithoutSectionInput[]
  createMany?: Prisma.TableCreateManySectionInputEnvelope
  connect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
}

export type TableUpdateManyWithoutSectionNestedInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutSectionInput, Prisma.TableUncheckedCreateWithoutSectionInput> | Prisma.TableCreateWithoutSectionInput[] | Prisma.TableUncheckedCreateWithoutSectionInput[]
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutSectionInput | Prisma.TableCreateOrConnectWithoutSectionInput[]
  upsert?: Prisma.TableUpsertWithWhereUniqueWithoutSectionInput | Prisma.TableUpsertWithWhereUniqueWithoutSectionInput[]
  createMany?: Prisma.TableCreateManySectionInputEnvelope
  set?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  disconnect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  delete?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  connect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  update?: Prisma.TableUpdateWithWhereUniqueWithoutSectionInput | Prisma.TableUpdateWithWhereUniqueWithoutSectionInput[]
  updateMany?: Prisma.TableUpdateManyWithWhereWithoutSectionInput | Prisma.TableUpdateManyWithWhereWithoutSectionInput[]
  deleteMany?: Prisma.TableScalarWhereInput | Prisma.TableScalarWhereInput[]
}

export type TableUncheckedUpdateManyWithoutSectionNestedInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutSectionInput, Prisma.TableUncheckedCreateWithoutSectionInput> | Prisma.TableCreateWithoutSectionInput[] | Prisma.TableUncheckedCreateWithoutSectionInput[]
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutSectionInput | Prisma.TableCreateOrConnectWithoutSectionInput[]
  upsert?: Prisma.TableUpsertWithWhereUniqueWithoutSectionInput | Prisma.TableUpsertWithWhereUniqueWithoutSectionInput[]
  createMany?: Prisma.TableCreateManySectionInputEnvelope
  set?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  disconnect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  delete?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  connect?: Prisma.TableWhereUniqueInput | Prisma.TableWhereUniqueInput[]
  update?: Prisma.TableUpdateWithWhereUniqueWithoutSectionInput | Prisma.TableUpdateWithWhereUniqueWithoutSectionInput[]
  updateMany?: Prisma.TableUpdateManyWithWhereWithoutSectionInput | Prisma.TableUpdateManyWithWhereWithoutSectionInput[]
  deleteMany?: Prisma.TableScalarWhereInput | Prisma.TableScalarWhereInput[]
}

export type TableCreateNestedOneWithoutReservationsInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutReservationsInput, Prisma.TableUncheckedCreateWithoutReservationsInput>
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutReservationsInput
  connect?: Prisma.TableWhereUniqueInput
}

export type TableUpdateOneWithoutReservationsNestedInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutReservationsInput, Prisma.TableUncheckedCreateWithoutReservationsInput>
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutReservationsInput
  upsert?: Prisma.TableUpsertWithoutReservationsInput
  disconnect?: Prisma.TableWhereInput | boolean
  delete?: Prisma.TableWhereInput | boolean
  connect?: Prisma.TableWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TableUpdateToOneWithWhereWithoutReservationsInput, Prisma.TableUpdateWithoutReservationsInput>, Prisma.TableUncheckedUpdateWithoutReservationsInput>
}

export type TableCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutOrdersInput, Prisma.TableUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutOrdersInput
  connect?: Prisma.TableWhereUniqueInput
}

export type TableUpdateOneRequiredWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutOrdersInput, Prisma.TableUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.TableUpsertWithoutOrdersInput
  connect?: Prisma.TableWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TableUpdateToOneWithWhereWithoutOrdersInput, Prisma.TableUpdateWithoutOrdersInput>, Prisma.TableUncheckedUpdateWithoutOrdersInput>
}

export type TableCreateNestedOneWithoutBuzzerRequestsInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutBuzzerRequestsInput, Prisma.TableUncheckedCreateWithoutBuzzerRequestsInput>
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutBuzzerRequestsInput
  connect?: Prisma.TableWhereUniqueInput
}

export type TableUpdateOneRequiredWithoutBuzzerRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.TableCreateWithoutBuzzerRequestsInput, Prisma.TableUncheckedCreateWithoutBuzzerRequestsInput>
  connectOrCreate?: Prisma.TableCreateOrConnectWithoutBuzzerRequestsInput
  upsert?: Prisma.TableUpsertWithoutBuzzerRequestsInput
  connect?: Prisma.TableWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TableUpdateToOneWithWhereWithoutBuzzerRequestsInput, Prisma.TableUpdateWithoutBuzzerRequestsInput>, Prisma.TableUncheckedUpdateWithoutBuzzerRequestsInput>
}

export type TableCreateWithoutAssignedWaiterInput = {
  id?: string
  number: number
  capacity: number
  status?: string
  currentGuests?: number
  qrCode?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  section: Prisma.SectionCreateNestedOneWithoutTablesInput
  reservations?: Prisma.ReservationCreateNestedManyWithoutTableInput
  orders?: Prisma.OrderCreateNestedManyWithoutTableInput
  buzzerRequests?: Prisma.BuzzerRequestCreateNestedManyWithoutTableInput
}

export type TableUncheckedCreateWithoutAssignedWaiterInput = {
  id?: string
  number: number
  capacity: number
  sectionId: string
  status?: string
  currentGuests?: number
  qrCode?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutTableInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutTableInput
  buzzerRequests?: Prisma.BuzzerRequestUncheckedCreateNestedManyWithoutTableInput
}

export type TableCreateOrConnectWithoutAssignedWaiterInput = {
  where: Prisma.TableWhereUniqueInput
  create: Prisma.XOR<Prisma.TableCreateWithoutAssignedWaiterInput, Prisma.TableUncheckedCreateWithoutAssignedWaiterInput>
}

export type TableCreateManyAssignedWaiterInputEnvelope = {
  data: Prisma.TableCreateManyAssignedWaiterInput | Prisma.TableCreateManyAssignedWaiterInput[]
}

export type TableUpsertWithWhereUniqueWithoutAssignedWaiterInput = {
  where: Prisma.TableWhereUniqueInput
  update: Prisma.XOR<Prisma.TableUpdateWithoutAssignedWaiterInput, Prisma.TableUncheckedUpdateWithoutAssignedWaiterInput>
  create: Prisma.XOR<Prisma.TableCreateWithoutAssignedWaiterInput, Prisma.TableUncheckedCreateWithoutAssignedWaiterInput>
}

export type TableUpdateWithWhereUniqueWithoutAssignedWaiterInput = {
  where: Prisma.TableWhereUniqueInput
  data: Prisma.XOR<Prisma.TableUpdateWithoutAssignedWaiterInput, Prisma.TableUncheckedUpdateWithoutAssignedWaiterInput>
}

export type TableUpdateManyWithWhereWithoutAssignedWaiterInput = {
  where: Prisma.TableScalarWhereInput
  data: Prisma.XOR<Prisma.TableUpdateManyMutationInput, Prisma.TableUncheckedUpdateManyWithoutAssignedWaiterInput>
}

export type TableScalarWhereInput = {
  AND?: Prisma.TableScalarWhereInput | Prisma.TableScalarWhereInput[]
  OR?: Prisma.TableScalarWhereInput[]
  NOT?: Prisma.TableScalarWhereInput | Prisma.TableScalarWhereInput[]
  id?: Prisma.StringFilter<"Table"> | string
  number?: Prisma.IntFilter<"Table"> | number
  capacity?: Prisma.IntFilter<"Table"> | number
  sectionId?: Prisma.StringFilter<"Table"> | string
  status?: Prisma.StringFilter<"Table"> | string
  currentGuests?: Prisma.IntFilter<"Table"> | number
  qrCode?: Prisma.StringNullableFilter<"Table"> | string | null
  assignedWaiterId?: Prisma.StringNullableFilter<"Table"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Table"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Table"> | Date | string
}

export type TableCreateWithoutSectionInput = {
  id?: string
  number: number
  capacity: number
  status?: string
  currentGuests?: number
  qrCode?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  reservations?: Prisma.ReservationCreateNestedManyWithoutTableInput
  orders?: Prisma.OrderCreateNestedManyWithoutTableInput
  assignedWaiter?: Prisma.StaffCreateNestedOneWithoutAssignedTablesInput
  buzzerRequests?: Prisma.BuzzerRequestCreateNestedManyWithoutTableInput
}

export type TableUncheckedCreateWithoutSectionInput = {
  id?: string
  number: number
  capacity: number
  status?: string
  currentGuests?: number
  qrCode?: string | null
  assignedWaiterId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutTableInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutTableInput
  buzzerRequests?: Prisma.BuzzerRequestUncheckedCreateNestedManyWithoutTableInput
}

export type TableCreateOrConnectWithoutSectionInput = {
  where: Prisma.TableWhereUniqueInput
  create: Prisma.XOR<Prisma.TableCreateWithoutSectionInput, Prisma.TableUncheckedCreateWithoutSectionInput>
}

export type TableCreateManySectionInputEnvelope = {
  data: Prisma.TableCreateManySectionInput | Prisma.TableCreateManySectionInput[]
}

export type TableUpsertWithWhereUniqueWithoutSectionInput = {
  where: Prisma.TableWhereUniqueInput
  update: Prisma.XOR<Prisma.TableUpdateWithoutSectionInput, Prisma.TableUncheckedUpdateWithoutSectionInput>
  create: Prisma.XOR<Prisma.TableCreateWithoutSectionInput, Prisma.TableUncheckedCreateWithoutSectionInput>
}

export type TableUpdateWithWhereUniqueWithoutSectionInput = {
  where: Prisma.TableWhereUniqueInput
  data: Prisma.XOR<Prisma.TableUpdateWithoutSectionInput, Prisma.TableUncheckedUpdateWithoutSectionInput>
}

export type TableUpdateManyWithWhereWithoutSectionInput = {
  where: Prisma.TableScalarWhereInput
  data: Prisma.XOR<Prisma.TableUpdateManyMutationInput, Prisma.TableUncheckedUpdateManyWithoutSectionInput>
}

export type TableCreateWithoutReservationsInput = {
  id?: string
  number: number
  capacity: number
  status?: string
  currentGuests?: number
  qrCode?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  section: Prisma.SectionCreateNestedOneWithoutTablesInput
  orders?: Prisma.OrderCreateNestedManyWithoutTableInput
  assignedWaiter?: Prisma.StaffCreateNestedOneWithoutAssignedTablesInput
  buzzerRequests?: Prisma.BuzzerRequestCreateNestedManyWithoutTableInput
}

export type TableUncheckedCreateWithoutReservationsInput = {
  id?: string
  number: number
  capacity: number
  sectionId: string
  status?: string
  currentGuests?: number
  qrCode?: string | null
  assignedWaiterId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutTableInput
  buzzerRequests?: Prisma.BuzzerRequestUncheckedCreateNestedManyWithoutTableInput
}

export type TableCreateOrConnectWithoutReservationsInput = {
  where: Prisma.TableWhereUniqueInput
  create: Prisma.XOR<Prisma.TableCreateWithoutReservationsInput, Prisma.TableUncheckedCreateWithoutReservationsInput>
}

export type TableUpsertWithoutReservationsInput = {
  update: Prisma.XOR<Prisma.TableUpdateWithoutReservationsInput, Prisma.TableUncheckedUpdateWithoutReservationsInput>
  create: Prisma.XOR<Prisma.TableCreateWithoutReservationsInput, Prisma.TableUncheckedCreateWithoutReservationsInput>
  where?: Prisma.TableWhereInput
}

export type TableUpdateToOneWithWhereWithoutReservationsInput = {
  where?: Prisma.TableWhereInput
  data: Prisma.XOR<Prisma.TableUpdateWithoutReservationsInput, Prisma.TableUncheckedUpdateWithoutReservationsInput>
}

export type TableUpdateWithoutReservationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  section?: Prisma.SectionUpdateOneRequiredWithoutTablesNestedInput
  orders?: Prisma.OrderUpdateManyWithoutTableNestedInput
  assignedWaiter?: Prisma.StaffUpdateOneWithoutAssignedTablesNestedInput
  buzzerRequests?: Prisma.BuzzerRequestUpdateManyWithoutTableNestedInput
}

export type TableUncheckedUpdateWithoutReservationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedWaiterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orders?: Prisma.OrderUncheckedUpdateManyWithoutTableNestedInput
  buzzerRequests?: Prisma.BuzzerRequestUncheckedUpdateManyWithoutTableNestedInput
}

export type TableCreateWithoutOrdersInput = {
  id?: string
  number: number
  capacity: number
  status?: string
  currentGuests?: number
  qrCode?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  section: Prisma.SectionCreateNestedOneWithoutTablesInput
  reservations?: Prisma.ReservationCreateNestedManyWithoutTableInput
  assignedWaiter?: Prisma.StaffCreateNestedOneWithoutAssignedTablesInput
  buzzerRequests?: Prisma.BuzzerRequestCreateNestedManyWithoutTableInput
}

export type TableUncheckedCreateWithoutOrdersInput = {
  id?: string
  number: number
  capacity: number
  sectionId: string
  status?: string
  currentGuests?: number
  qrCode?: string | null
  assignedWaiterId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutTableInput
  buzzerRequests?: Prisma.BuzzerRequestUncheckedCreateNestedManyWithoutTableInput
}

export type TableCreateOrConnectWithoutOrdersInput = {
  where: Prisma.TableWhereUniqueInput
  create: Prisma.XOR<Prisma.TableCreateWithoutOrdersInput, Prisma.TableUncheckedCreateWithoutOrdersInput>
}

export type TableUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.TableUpdateWithoutOrdersInput, Prisma.TableUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.TableCreateWithoutOrdersInput, Prisma.TableUncheckedCreateWithoutOrdersInput>
  where?: Prisma.TableWhereInput
}

export type TableUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.TableWhereInput
  data: Prisma.XOR<Prisma.TableUpdateWithoutOrdersInput, Prisma.TableUncheckedUpdateWithoutOrdersInput>
}

export type TableUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  section?: Prisma.SectionUpdateOneRequiredWithoutTablesNestedInput
  reservations?: Prisma.ReservationUpdateManyWithoutTableNestedInput
  assignedWaiter?: Prisma.StaffUpdateOneWithoutAssignedTablesNestedInput
  buzzerRequests?: Prisma.BuzzerRequestUpdateManyWithoutTableNestedInput
}

export type TableUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedWaiterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutTableNestedInput
  buzzerRequests?: Prisma.BuzzerRequestUncheckedUpdateManyWithoutTableNestedInput
}

export type TableCreateWithoutBuzzerRequestsInput = {
  id?: string
  number: number
  capacity: number
  status?: string
  currentGuests?: number
  qrCode?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  section: Prisma.SectionCreateNestedOneWithoutTablesInput
  reservations?: Prisma.ReservationCreateNestedManyWithoutTableInput
  orders?: Prisma.OrderCreateNestedManyWithoutTableInput
  assignedWaiter?: Prisma.StaffCreateNestedOneWithoutAssignedTablesInput
}

export type TableUncheckedCreateWithoutBuzzerRequestsInput = {
  id?: string
  number: number
  capacity: number
  sectionId: string
  status?: string
  currentGuests?: number
  qrCode?: string | null
  assignedWaiterId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutTableInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutTableInput
}

export type TableCreateOrConnectWithoutBuzzerRequestsInput = {
  where: Prisma.TableWhereUniqueInput
  create: Prisma.XOR<Prisma.TableCreateWithoutBuzzerRequestsInput, Prisma.TableUncheckedCreateWithoutBuzzerRequestsInput>
}

export type TableUpsertWithoutBuzzerRequestsInput = {
  update: Prisma.XOR<Prisma.TableUpdateWithoutBuzzerRequestsInput, Prisma.TableUncheckedUpdateWithoutBuzzerRequestsInput>
  create: Prisma.XOR<Prisma.TableCreateWithoutBuzzerRequestsInput, Prisma.TableUncheckedCreateWithoutBuzzerRequestsInput>
  where?: Prisma.TableWhereInput
}

export type TableUpdateToOneWithWhereWithoutBuzzerRequestsInput = {
  where?: Prisma.TableWhereInput
  data: Prisma.XOR<Prisma.TableUpdateWithoutBuzzerRequestsInput, Prisma.TableUncheckedUpdateWithoutBuzzerRequestsInput>
}

export type TableUpdateWithoutBuzzerRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  section?: Prisma.SectionUpdateOneRequiredWithoutTablesNestedInput
  reservations?: Prisma.ReservationUpdateManyWithoutTableNestedInput
  orders?: Prisma.OrderUpdateManyWithoutTableNestedInput
  assignedWaiter?: Prisma.StaffUpdateOneWithoutAssignedTablesNestedInput
}

export type TableUncheckedUpdateWithoutBuzzerRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedWaiterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutTableNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutTableNestedInput
}

export type TableCreateManyAssignedWaiterInput = {
  id?: string
  number: number
  capacity: number
  sectionId: string
  status?: string
  currentGuests?: number
  qrCode?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TableUpdateWithoutAssignedWaiterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  section?: Prisma.SectionUpdateOneRequiredWithoutTablesNestedInput
  reservations?: Prisma.ReservationUpdateManyWithoutTableNestedInput
  orders?: Prisma.OrderUpdateManyWithoutTableNestedInput
  buzzerRequests?: Prisma.BuzzerRequestUpdateManyWithoutTableNestedInput
}

export type TableUncheckedUpdateWithoutAssignedWaiterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutTableNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutTableNestedInput
  buzzerRequests?: Prisma.BuzzerRequestUncheckedUpdateManyWithoutTableNestedInput
}

export type TableUncheckedUpdateManyWithoutAssignedWaiterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  sectionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TableCreateManySectionInput = {
  id?: string
  number: number
  capacity: number
  status?: string
  currentGuests?: number
  qrCode?: string | null
  assignedWaiterId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TableUpdateWithoutSectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservations?: Prisma.ReservationUpdateManyWithoutTableNestedInput
  orders?: Prisma.OrderUpdateManyWithoutTableNestedInput
  assignedWaiter?: Prisma.StaffUpdateOneWithoutAssignedTablesNestedInput
  buzzerRequests?: Prisma.BuzzerRequestUpdateManyWithoutTableNestedInput
}

export type TableUncheckedUpdateWithoutSectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedWaiterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutTableNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutTableNestedInput
  buzzerRequests?: Prisma.BuzzerRequestUncheckedUpdateManyWithoutTableNestedInput
}

export type TableUncheckedUpdateManyWithoutSectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  currentGuests?: Prisma.IntFieldUpdateOperationsInput | number
  qrCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedWaiterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TableCountOutputType
 */

export type TableCountOutputType = {
  reservations: number
  orders: number
  buzzerRequests: number
}

export type TableCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reservations?: boolean | TableCountOutputTypeCountReservationsArgs
  orders?: boolean | TableCountOutputTypeCountOrdersArgs
  buzzerRequests?: boolean | TableCountOutputTypeCountBuzzerRequestsArgs
}

/**
 * TableCountOutputType without action
 */
export type TableCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TableCountOutputType
   */
  select?: Prisma.TableCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TableCountOutputType without action
 */
export type TableCountOutputTypeCountReservationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReservationWhereInput
}

/**
 * TableCountOutputType without action
 */
export type TableCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}

/**
 * TableCountOutputType without action
 */
export type TableCountOutputTypeCountBuzzerRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BuzzerRequestWhereInput
}


export type TableSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  number?: boolean
  capacity?: boolean
  sectionId?: boolean
  status?: boolean
  currentGuests?: boolean
  qrCode?: boolean
  assignedWaiterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  section?: boolean | Prisma.SectionDefaultArgs<ExtArgs>
  reservations?: boolean | Prisma.Table$reservationsArgs<ExtArgs>
  orders?: boolean | Prisma.Table$ordersArgs<ExtArgs>
  assignedWaiter?: boolean | Prisma.Table$assignedWaiterArgs<ExtArgs>
  buzzerRequests?: boolean | Prisma.Table$buzzerRequestsArgs<ExtArgs>
  _count?: boolean | Prisma.TableCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["table"]>

export type TableSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  number?: boolean
  capacity?: boolean
  sectionId?: boolean
  status?: boolean
  currentGuests?: boolean
  qrCode?: boolean
  assignedWaiterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  section?: boolean | Prisma.SectionDefaultArgs<ExtArgs>
  assignedWaiter?: boolean | Prisma.Table$assignedWaiterArgs<ExtArgs>
}, ExtArgs["result"]["table"]>

export type TableSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  number?: boolean
  capacity?: boolean
  sectionId?: boolean
  status?: boolean
  currentGuests?: boolean
  qrCode?: boolean
  assignedWaiterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  section?: boolean | Prisma.SectionDefaultArgs<ExtArgs>
  assignedWaiter?: boolean | Prisma.Table$assignedWaiterArgs<ExtArgs>
}, ExtArgs["result"]["table"]>

export type TableSelectScalar = {
  id?: boolean
  number?: boolean
  capacity?: boolean
  sectionId?: boolean
  status?: boolean
  currentGuests?: boolean
  qrCode?: boolean
  assignedWaiterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TableOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "number" | "capacity" | "sectionId" | "status" | "currentGuests" | "qrCode" | "assignedWaiterId" | "createdAt" | "updatedAt", ExtArgs["result"]["table"]>
export type TableInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  section?: boolean | Prisma.SectionDefaultArgs<ExtArgs>
  reservations?: boolean | Prisma.Table$reservationsArgs<ExtArgs>
  orders?: boolean | Prisma.Table$ordersArgs<ExtArgs>
  assignedWaiter?: boolean | Prisma.Table$assignedWaiterArgs<ExtArgs>
  buzzerRequests?: boolean | Prisma.Table$buzzerRequestsArgs<ExtArgs>
  _count?: boolean | Prisma.TableCountOutputTypeDefaultArgs<ExtArgs>
}
export type TableIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  section?: boolean | Prisma.SectionDefaultArgs<ExtArgs>
  assignedWaiter?: boolean | Prisma.Table$assignedWaiterArgs<ExtArgs>
}
export type TableIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  section?: boolean | Prisma.SectionDefaultArgs<ExtArgs>
  assignedWaiter?: boolean | Prisma.Table$assignedWaiterArgs<ExtArgs>
}

export type $TablePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Table"
  objects: {
    section: Prisma.$SectionPayload<ExtArgs>
    reservations: Prisma.$ReservationPayload<ExtArgs>[]
    orders: Prisma.$OrderPayload<ExtArgs>[]
    assignedWaiter: Prisma.$StaffPayload<ExtArgs> | null
    buzzerRequests: Prisma.$BuzzerRequestPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    number: number
    capacity: number
    sectionId: string
    status: string
    currentGuests: number
    qrCode: string | null
    assignedWaiterId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["table"]>
  composites: {}
}

export type TableGetPayload<S extends boolean | null | undefined | TableDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TablePayload, S>

export type TableCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TableFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TableCountAggregateInputType | true
  }

export interface TableDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Table'], meta: { name: 'Table' } }
  /**
   * Find zero or one Table that matches the filter.
   * @param {TableFindUniqueArgs} args - Arguments to find a Table
   * @example
   * // Get one Table
   * const table = await prisma.table.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TableFindUniqueArgs>(args: Prisma.SelectSubset<T, TableFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TableClient<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Table that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TableFindUniqueOrThrowArgs} args - Arguments to find a Table
   * @example
   * // Get one Table
   * const table = await prisma.table.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TableFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TableFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TableClient<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Table that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableFindFirstArgs} args - Arguments to find a Table
   * @example
   * // Get one Table
   * const table = await prisma.table.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TableFindFirstArgs>(args?: Prisma.SelectSubset<T, TableFindFirstArgs<ExtArgs>>): Prisma.Prisma__TableClient<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Table that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableFindFirstOrThrowArgs} args - Arguments to find a Table
   * @example
   * // Get one Table
   * const table = await prisma.table.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TableFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TableFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TableClient<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tables that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tables
   * const tables = await prisma.table.findMany()
   * 
   * // Get first 10 Tables
   * const tables = await prisma.table.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tableWithIdOnly = await prisma.table.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TableFindManyArgs>(args?: Prisma.SelectSubset<T, TableFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Table.
   * @param {TableCreateArgs} args - Arguments to create a Table.
   * @example
   * // Create one Table
   * const Table = await prisma.table.create({
   *   data: {
   *     // ... data to create a Table
   *   }
   * })
   * 
   */
  create<T extends TableCreateArgs>(args: Prisma.SelectSubset<T, TableCreateArgs<ExtArgs>>): Prisma.Prisma__TableClient<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tables.
   * @param {TableCreateManyArgs} args - Arguments to create many Tables.
   * @example
   * // Create many Tables
   * const table = await prisma.table.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TableCreateManyArgs>(args?: Prisma.SelectSubset<T, TableCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tables and returns the data saved in the database.
   * @param {TableCreateManyAndReturnArgs} args - Arguments to create many Tables.
   * @example
   * // Create many Tables
   * const table = await prisma.table.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tables and only return the `id`
   * const tableWithIdOnly = await prisma.table.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TableCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TableCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Table.
   * @param {TableDeleteArgs} args - Arguments to delete one Table.
   * @example
   * // Delete one Table
   * const Table = await prisma.table.delete({
   *   where: {
   *     // ... filter to delete one Table
   *   }
   * })
   * 
   */
  delete<T extends TableDeleteArgs>(args: Prisma.SelectSubset<T, TableDeleteArgs<ExtArgs>>): Prisma.Prisma__TableClient<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Table.
   * @param {TableUpdateArgs} args - Arguments to update one Table.
   * @example
   * // Update one Table
   * const table = await prisma.table.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TableUpdateArgs>(args: Prisma.SelectSubset<T, TableUpdateArgs<ExtArgs>>): Prisma.Prisma__TableClient<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tables.
   * @param {TableDeleteManyArgs} args - Arguments to filter Tables to delete.
   * @example
   * // Delete a few Tables
   * const { count } = await prisma.table.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TableDeleteManyArgs>(args?: Prisma.SelectSubset<T, TableDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tables.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tables
   * const table = await prisma.table.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TableUpdateManyArgs>(args: Prisma.SelectSubset<T, TableUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tables and returns the data updated in the database.
   * @param {TableUpdateManyAndReturnArgs} args - Arguments to update many Tables.
   * @example
   * // Update many Tables
   * const table = await prisma.table.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tables and only return the `id`
   * const tableWithIdOnly = await prisma.table.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TableUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TableUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Table.
   * @param {TableUpsertArgs} args - Arguments to update or create a Table.
   * @example
   * // Update or create a Table
   * const table = await prisma.table.upsert({
   *   create: {
   *     // ... data to create a Table
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Table we want to update
   *   }
   * })
   */
  upsert<T extends TableUpsertArgs>(args: Prisma.SelectSubset<T, TableUpsertArgs<ExtArgs>>): Prisma.Prisma__TableClient<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tables.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableCountArgs} args - Arguments to filter Tables to count.
   * @example
   * // Count the number of Tables
   * const count = await prisma.table.count({
   *   where: {
   *     // ... the filter for the Tables we want to count
   *   }
   * })
  **/
  count<T extends TableCountArgs>(
    args?: Prisma.Subset<T, TableCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TableCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Table.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TableAggregateArgs>(args: Prisma.Subset<T, TableAggregateArgs>): Prisma.PrismaPromise<GetTableAggregateType<T>>

  /**
   * Group by Table.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TableGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TableGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TableGroupByArgs['orderBy'] }
      : { orderBy?: TableGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TableGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTableGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Table model
 */
readonly fields: TableFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Table.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TableClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  section<T extends Prisma.SectionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SectionDefaultArgs<ExtArgs>>): Prisma.Prisma__SectionClient<runtime.Types.Result.GetResult<Prisma.$SectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  reservations<T extends Prisma.Table$reservationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Table$reservationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReservationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  orders<T extends Prisma.Table$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Table$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  assignedWaiter<T extends Prisma.Table$assignedWaiterArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Table$assignedWaiterArgs<ExtArgs>>): Prisma.Prisma__StaffClient<runtime.Types.Result.GetResult<Prisma.$StaffPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  buzzerRequests<T extends Prisma.Table$buzzerRequestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Table$buzzerRequestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuzzerRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Table model
 */
export interface TableFieldRefs {
  readonly id: Prisma.FieldRef<"Table", 'String'>
  readonly number: Prisma.FieldRef<"Table", 'Int'>
  readonly capacity: Prisma.FieldRef<"Table", 'Int'>
  readonly sectionId: Prisma.FieldRef<"Table", 'String'>
  readonly status: Prisma.FieldRef<"Table", 'String'>
  readonly currentGuests: Prisma.FieldRef<"Table", 'Int'>
  readonly qrCode: Prisma.FieldRef<"Table", 'String'>
  readonly assignedWaiterId: Prisma.FieldRef<"Table", 'String'>
  readonly createdAt: Prisma.FieldRef<"Table", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Table", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Table findUnique
 */
export type TableFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
  /**
   * Filter, which Table to fetch.
   */
  where: Prisma.TableWhereUniqueInput
}

/**
 * Table findUniqueOrThrow
 */
export type TableFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
  /**
   * Filter, which Table to fetch.
   */
  where: Prisma.TableWhereUniqueInput
}

/**
 * Table findFirst
 */
export type TableFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
  /**
   * Filter, which Table to fetch.
   */
  where?: Prisma.TableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tables to fetch.
   */
  orderBy?: Prisma.TableOrderByWithRelationInput | Prisma.TableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tables.
   */
  cursor?: Prisma.TableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tables.
   */
  distinct?: Prisma.TableScalarFieldEnum | Prisma.TableScalarFieldEnum[]
}

/**
 * Table findFirstOrThrow
 */
export type TableFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
  /**
   * Filter, which Table to fetch.
   */
  where?: Prisma.TableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tables to fetch.
   */
  orderBy?: Prisma.TableOrderByWithRelationInput | Prisma.TableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tables.
   */
  cursor?: Prisma.TableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tables.
   */
  distinct?: Prisma.TableScalarFieldEnum | Prisma.TableScalarFieldEnum[]
}

/**
 * Table findMany
 */
export type TableFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
  /**
   * Filter, which Tables to fetch.
   */
  where?: Prisma.TableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tables to fetch.
   */
  orderBy?: Prisma.TableOrderByWithRelationInput | Prisma.TableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tables.
   */
  cursor?: Prisma.TableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tables.
   */
  skip?: number
  distinct?: Prisma.TableScalarFieldEnum | Prisma.TableScalarFieldEnum[]
}

/**
 * Table create
 */
export type TableCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
  /**
   * The data needed to create a Table.
   */
  data: Prisma.XOR<Prisma.TableCreateInput, Prisma.TableUncheckedCreateInput>
}

/**
 * Table createMany
 */
export type TableCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tables.
   */
  data: Prisma.TableCreateManyInput | Prisma.TableCreateManyInput[]
}

/**
 * Table createManyAndReturn
 */
export type TableCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * The data used to create many Tables.
   */
  data: Prisma.TableCreateManyInput | Prisma.TableCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Table update
 */
export type TableUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
  /**
   * The data needed to update a Table.
   */
  data: Prisma.XOR<Prisma.TableUpdateInput, Prisma.TableUncheckedUpdateInput>
  /**
   * Choose, which Table to update.
   */
  where: Prisma.TableWhereUniqueInput
}

/**
 * Table updateMany
 */
export type TableUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tables.
   */
  data: Prisma.XOR<Prisma.TableUpdateManyMutationInput, Prisma.TableUncheckedUpdateManyInput>
  /**
   * Filter which Tables to update
   */
  where?: Prisma.TableWhereInput
  /**
   * Limit how many Tables to update.
   */
  limit?: number
}

/**
 * Table updateManyAndReturn
 */
export type TableUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * The data used to update Tables.
   */
  data: Prisma.XOR<Prisma.TableUpdateManyMutationInput, Prisma.TableUncheckedUpdateManyInput>
  /**
   * Filter which Tables to update
   */
  where?: Prisma.TableWhereInput
  /**
   * Limit how many Tables to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Table upsert
 */
export type TableUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
  /**
   * The filter to search for the Table to update in case it exists.
   */
  where: Prisma.TableWhereUniqueInput
  /**
   * In case the Table found by the `where` argument doesn't exist, create a new Table with this data.
   */
  create: Prisma.XOR<Prisma.TableCreateInput, Prisma.TableUncheckedCreateInput>
  /**
   * In case the Table was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TableUpdateInput, Prisma.TableUncheckedUpdateInput>
}

/**
 * Table delete
 */
export type TableDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
  /**
   * Filter which Table to delete.
   */
  where: Prisma.TableWhereUniqueInput
}

/**
 * Table deleteMany
 */
export type TableDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tables to delete
   */
  where?: Prisma.TableWhereInput
  /**
   * Limit how many Tables to delete.
   */
  limit?: number
}

/**
 * Table.reservations
 */
export type Table$reservationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reservation
   */
  select?: Prisma.ReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reservation
   */
  omit?: Prisma.ReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReservationInclude<ExtArgs> | null
  where?: Prisma.ReservationWhereInput
  orderBy?: Prisma.ReservationOrderByWithRelationInput | Prisma.ReservationOrderByWithRelationInput[]
  cursor?: Prisma.ReservationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReservationScalarFieldEnum | Prisma.ReservationScalarFieldEnum[]
}

/**
 * Table.orders
 */
export type Table$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Table.assignedWaiter
 */
export type Table$assignedWaiterArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Staff
   */
  select?: Prisma.StaffSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Staff
   */
  omit?: Prisma.StaffOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StaffInclude<ExtArgs> | null
  where?: Prisma.StaffWhereInput
}

/**
 * Table.buzzerRequests
 */
export type Table$buzzerRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuzzerRequest
   */
  select?: Prisma.BuzzerRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuzzerRequest
   */
  omit?: Prisma.BuzzerRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuzzerRequestInclude<ExtArgs> | null
  where?: Prisma.BuzzerRequestWhereInput
  orderBy?: Prisma.BuzzerRequestOrderByWithRelationInput | Prisma.BuzzerRequestOrderByWithRelationInput[]
  cursor?: Prisma.BuzzerRequestWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BuzzerRequestScalarFieldEnum | Prisma.BuzzerRequestScalarFieldEnum[]
}

/**
 * Table without action
 */
export type TableDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
}
