
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TaxPeriod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TaxPeriod
 * 
 */
export type TaxPeriodModel = runtime.Types.Result.DefaultSelection<Prisma.$TaxPeriodPayload>

export type AggregateTaxPeriod = {
  _count: TaxPeriodCountAggregateOutputType | null
  _avg: TaxPeriodAvgAggregateOutputType | null
  _sum: TaxPeriodSumAggregateOutputType | null
  _min: TaxPeriodMinAggregateOutputType | null
  _max: TaxPeriodMaxAggregateOutputType | null
}

export type TaxPeriodAvgAggregateOutputType = {
  quarter: number | null
  year: number | null
}

export type TaxPeriodSumAggregateOutputType = {
  quarter: number | null
  year: number | null
}

export type TaxPeriodMinAggregateOutputType = {
  id: string | null
  startDate: Date | null
  endDate: Date | null
  quarter: number | null
  year: number | null
  status: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TaxPeriodMaxAggregateOutputType = {
  id: string | null
  startDate: Date | null
  endDate: Date | null
  quarter: number | null
  year: number | null
  status: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TaxPeriodCountAggregateOutputType = {
  id: number
  startDate: number
  endDate: number
  quarter: number
  year: number
  status: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TaxPeriodAvgAggregateInputType = {
  quarter?: true
  year?: true
}

export type TaxPeriodSumAggregateInputType = {
  quarter?: true
  year?: true
}

export type TaxPeriodMinAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  quarter?: true
  year?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type TaxPeriodMaxAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  quarter?: true
  year?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type TaxPeriodCountAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  quarter?: true
  year?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TaxPeriodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaxPeriod to aggregate.
   */
  where?: Prisma.TaxPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxPeriods to fetch.
   */
  orderBy?: Prisma.TaxPeriodOrderByWithRelationInput | Prisma.TaxPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TaxPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TaxPeriods
  **/
  _count?: true | TaxPeriodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TaxPeriodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TaxPeriodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TaxPeriodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TaxPeriodMaxAggregateInputType
}

export type GetTaxPeriodAggregateType<T extends TaxPeriodAggregateArgs> = {
      [P in keyof T & keyof AggregateTaxPeriod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTaxPeriod[P]>
    : Prisma.GetScalarType<T[P], AggregateTaxPeriod[P]>
}




export type TaxPeriodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaxPeriodWhereInput
  orderBy?: Prisma.TaxPeriodOrderByWithAggregationInput | Prisma.TaxPeriodOrderByWithAggregationInput[]
  by: Prisma.TaxPeriodScalarFieldEnum[] | Prisma.TaxPeriodScalarFieldEnum
  having?: Prisma.TaxPeriodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TaxPeriodCountAggregateInputType | true
  _avg?: TaxPeriodAvgAggregateInputType
  _sum?: TaxPeriodSumAggregateInputType
  _min?: TaxPeriodMinAggregateInputType
  _max?: TaxPeriodMaxAggregateInputType
}

export type TaxPeriodGroupByOutputType = {
  id: string
  startDate: Date
  endDate: Date
  quarter: number
  year: number
  status: string
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: TaxPeriodCountAggregateOutputType | null
  _avg: TaxPeriodAvgAggregateOutputType | null
  _sum: TaxPeriodSumAggregateOutputType | null
  _min: TaxPeriodMinAggregateOutputType | null
  _max: TaxPeriodMaxAggregateOutputType | null
}

type GetTaxPeriodGroupByPayload<T extends TaxPeriodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TaxPeriodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TaxPeriodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TaxPeriodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TaxPeriodGroupByOutputType[P]>
      }
    >
  >



export type TaxPeriodWhereInput = {
  AND?: Prisma.TaxPeriodWhereInput | Prisma.TaxPeriodWhereInput[]
  OR?: Prisma.TaxPeriodWhereInput[]
  NOT?: Prisma.TaxPeriodWhereInput | Prisma.TaxPeriodWhereInput[]
  id?: Prisma.StringFilter<"TaxPeriod"> | string
  startDate?: Prisma.DateTimeFilter<"TaxPeriod"> | Date | string
  endDate?: Prisma.DateTimeFilter<"TaxPeriod"> | Date | string
  quarter?: Prisma.IntFilter<"TaxPeriod"> | number
  year?: Prisma.IntFilter<"TaxPeriod"> | number
  status?: Prisma.StringFilter<"TaxPeriod"> | string
  notes?: Prisma.StringNullableFilter<"TaxPeriod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TaxPeriod"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TaxPeriod"> | Date | string
  vatReturns?: Prisma.VATReturnListRelationFilter
}

export type TaxPeriodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  quarter?: Prisma.SortOrder
  year?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  vatReturns?: Prisma.VATReturnOrderByRelationAggregateInput
}

export type TaxPeriodWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TaxPeriodWhereInput | Prisma.TaxPeriodWhereInput[]
  OR?: Prisma.TaxPeriodWhereInput[]
  NOT?: Prisma.TaxPeriodWhereInput | Prisma.TaxPeriodWhereInput[]
  startDate?: Prisma.DateTimeFilter<"TaxPeriod"> | Date | string
  endDate?: Prisma.DateTimeFilter<"TaxPeriod"> | Date | string
  quarter?: Prisma.IntFilter<"TaxPeriod"> | number
  year?: Prisma.IntFilter<"TaxPeriod"> | number
  status?: Prisma.StringFilter<"TaxPeriod"> | string
  notes?: Prisma.StringNullableFilter<"TaxPeriod"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TaxPeriod"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TaxPeriod"> | Date | string
  vatReturns?: Prisma.VATReturnListRelationFilter
}, "id">

export type TaxPeriodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  quarter?: Prisma.SortOrder
  year?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TaxPeriodCountOrderByAggregateInput
  _avg?: Prisma.TaxPeriodAvgOrderByAggregateInput
  _max?: Prisma.TaxPeriodMaxOrderByAggregateInput
  _min?: Prisma.TaxPeriodMinOrderByAggregateInput
  _sum?: Prisma.TaxPeriodSumOrderByAggregateInput
}

export type TaxPeriodScalarWhereWithAggregatesInput = {
  AND?: Prisma.TaxPeriodScalarWhereWithAggregatesInput | Prisma.TaxPeriodScalarWhereWithAggregatesInput[]
  OR?: Prisma.TaxPeriodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TaxPeriodScalarWhereWithAggregatesInput | Prisma.TaxPeriodScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TaxPeriod"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"TaxPeriod"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"TaxPeriod"> | Date | string
  quarter?: Prisma.IntWithAggregatesFilter<"TaxPeriod"> | number
  year?: Prisma.IntWithAggregatesFilter<"TaxPeriod"> | number
  status?: Prisma.StringWithAggregatesFilter<"TaxPeriod"> | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"TaxPeriod"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TaxPeriod"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TaxPeriod"> | Date | string
}

export type TaxPeriodCreateInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  quarter: number
  year: number
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  vatReturns?: Prisma.VATReturnCreateNestedManyWithoutTaxPeriodInput
}

export type TaxPeriodUncheckedCreateInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  quarter: number
  year: number
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  vatReturns?: Prisma.VATReturnUncheckedCreateNestedManyWithoutTaxPeriodInput
}

export type TaxPeriodUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quarter?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  vatReturns?: Prisma.VATReturnUpdateManyWithoutTaxPeriodNestedInput
}

export type TaxPeriodUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quarter?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  vatReturns?: Prisma.VATReturnUncheckedUpdateManyWithoutTaxPeriodNestedInput
}

export type TaxPeriodCreateManyInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  quarter: number
  year: number
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TaxPeriodUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quarter?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxPeriodUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quarter?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxPeriodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  quarter?: Prisma.SortOrder
  year?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TaxPeriodAvgOrderByAggregateInput = {
  quarter?: Prisma.SortOrder
  year?: Prisma.SortOrder
}

export type TaxPeriodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  quarter?: Prisma.SortOrder
  year?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TaxPeriodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  quarter?: Prisma.SortOrder
  year?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TaxPeriodSumOrderByAggregateInput = {
  quarter?: Prisma.SortOrder
  year?: Prisma.SortOrder
}

export type TaxPeriodScalarRelationFilter = {
  is?: Prisma.TaxPeriodWhereInput
  isNot?: Prisma.TaxPeriodWhereInput
}

export type TaxPeriodCreateNestedOneWithoutVatReturnsInput = {
  create?: Prisma.XOR<Prisma.TaxPeriodCreateWithoutVatReturnsInput, Prisma.TaxPeriodUncheckedCreateWithoutVatReturnsInput>
  connectOrCreate?: Prisma.TaxPeriodCreateOrConnectWithoutVatReturnsInput
  connect?: Prisma.TaxPeriodWhereUniqueInput
}

export type TaxPeriodUpdateOneRequiredWithoutVatReturnsNestedInput = {
  create?: Prisma.XOR<Prisma.TaxPeriodCreateWithoutVatReturnsInput, Prisma.TaxPeriodUncheckedCreateWithoutVatReturnsInput>
  connectOrCreate?: Prisma.TaxPeriodCreateOrConnectWithoutVatReturnsInput
  upsert?: Prisma.TaxPeriodUpsertWithoutVatReturnsInput
  connect?: Prisma.TaxPeriodWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TaxPeriodUpdateToOneWithWhereWithoutVatReturnsInput, Prisma.TaxPeriodUpdateWithoutVatReturnsInput>, Prisma.TaxPeriodUncheckedUpdateWithoutVatReturnsInput>
}

export type TaxPeriodCreateWithoutVatReturnsInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  quarter: number
  year: number
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TaxPeriodUncheckedCreateWithoutVatReturnsInput = {
  id?: string
  startDate: Date | string
  endDate: Date | string
  quarter: number
  year: number
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TaxPeriodCreateOrConnectWithoutVatReturnsInput = {
  where: Prisma.TaxPeriodWhereUniqueInput
  create: Prisma.XOR<Prisma.TaxPeriodCreateWithoutVatReturnsInput, Prisma.TaxPeriodUncheckedCreateWithoutVatReturnsInput>
}

export type TaxPeriodUpsertWithoutVatReturnsInput = {
  update: Prisma.XOR<Prisma.TaxPeriodUpdateWithoutVatReturnsInput, Prisma.TaxPeriodUncheckedUpdateWithoutVatReturnsInput>
  create: Prisma.XOR<Prisma.TaxPeriodCreateWithoutVatReturnsInput, Prisma.TaxPeriodUncheckedCreateWithoutVatReturnsInput>
  where?: Prisma.TaxPeriodWhereInput
}

export type TaxPeriodUpdateToOneWithWhereWithoutVatReturnsInput = {
  where?: Prisma.TaxPeriodWhereInput
  data: Prisma.XOR<Prisma.TaxPeriodUpdateWithoutVatReturnsInput, Prisma.TaxPeriodUncheckedUpdateWithoutVatReturnsInput>
}

export type TaxPeriodUpdateWithoutVatReturnsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quarter?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxPeriodUncheckedUpdateWithoutVatReturnsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quarter?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TaxPeriodCountOutputType
 */

export type TaxPeriodCountOutputType = {
  vatReturns: number
}

export type TaxPeriodCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vatReturns?: boolean | TaxPeriodCountOutputTypeCountVatReturnsArgs
}

/**
 * TaxPeriodCountOutputType without action
 */
export type TaxPeriodCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriodCountOutputType
   */
  select?: Prisma.TaxPeriodCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TaxPeriodCountOutputType without action
 */
export type TaxPeriodCountOutputTypeCountVatReturnsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VATReturnWhereInput
}


export type TaxPeriodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  quarter?: boolean
  year?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  vatReturns?: boolean | Prisma.TaxPeriod$vatReturnsArgs<ExtArgs>
  _count?: boolean | Prisma.TaxPeriodCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taxPeriod"]>

export type TaxPeriodSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  quarter?: boolean
  year?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["taxPeriod"]>

export type TaxPeriodSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  quarter?: boolean
  year?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["taxPeriod"]>

export type TaxPeriodSelectScalar = {
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  quarter?: boolean
  year?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TaxPeriodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "startDate" | "endDate" | "quarter" | "year" | "status" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["taxPeriod"]>
export type TaxPeriodInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vatReturns?: boolean | Prisma.TaxPeriod$vatReturnsArgs<ExtArgs>
  _count?: boolean | Prisma.TaxPeriodCountOutputTypeDefaultArgs<ExtArgs>
}
export type TaxPeriodIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TaxPeriodIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TaxPeriodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TaxPeriod"
  objects: {
    vatReturns: Prisma.$VATReturnPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    startDate: Date
    endDate: Date
    quarter: number
    year: number
    status: string
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["taxPeriod"]>
  composites: {}
}

export type TaxPeriodGetPayload<S extends boolean | null | undefined | TaxPeriodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload, S>

export type TaxPeriodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TaxPeriodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TaxPeriodCountAggregateInputType | true
  }

export interface TaxPeriodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TaxPeriod'], meta: { name: 'TaxPeriod' } }
  /**
   * Find zero or one TaxPeriod that matches the filter.
   * @param {TaxPeriodFindUniqueArgs} args - Arguments to find a TaxPeriod
   * @example
   * // Get one TaxPeriod
   * const taxPeriod = await prisma.taxPeriod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TaxPeriodFindUniqueArgs>(args: Prisma.SelectSubset<T, TaxPeriodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TaxPeriodClient<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TaxPeriod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TaxPeriodFindUniqueOrThrowArgs} args - Arguments to find a TaxPeriod
   * @example
   * // Get one TaxPeriod
   * const taxPeriod = await prisma.taxPeriod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TaxPeriodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TaxPeriodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaxPeriodClient<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaxPeriod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxPeriodFindFirstArgs} args - Arguments to find a TaxPeriod
   * @example
   * // Get one TaxPeriod
   * const taxPeriod = await prisma.taxPeriod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TaxPeriodFindFirstArgs>(args?: Prisma.SelectSubset<T, TaxPeriodFindFirstArgs<ExtArgs>>): Prisma.Prisma__TaxPeriodClient<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaxPeriod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxPeriodFindFirstOrThrowArgs} args - Arguments to find a TaxPeriod
   * @example
   * // Get one TaxPeriod
   * const taxPeriod = await prisma.taxPeriod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TaxPeriodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TaxPeriodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaxPeriodClient<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TaxPeriods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxPeriodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TaxPeriods
   * const taxPeriods = await prisma.taxPeriod.findMany()
   * 
   * // Get first 10 TaxPeriods
   * const taxPeriods = await prisma.taxPeriod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const taxPeriodWithIdOnly = await prisma.taxPeriod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TaxPeriodFindManyArgs>(args?: Prisma.SelectSubset<T, TaxPeriodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TaxPeriod.
   * @param {TaxPeriodCreateArgs} args - Arguments to create a TaxPeriod.
   * @example
   * // Create one TaxPeriod
   * const TaxPeriod = await prisma.taxPeriod.create({
   *   data: {
   *     // ... data to create a TaxPeriod
   *   }
   * })
   * 
   */
  create<T extends TaxPeriodCreateArgs>(args: Prisma.SelectSubset<T, TaxPeriodCreateArgs<ExtArgs>>): Prisma.Prisma__TaxPeriodClient<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TaxPeriods.
   * @param {TaxPeriodCreateManyArgs} args - Arguments to create many TaxPeriods.
   * @example
   * // Create many TaxPeriods
   * const taxPeriod = await prisma.taxPeriod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TaxPeriodCreateManyArgs>(args?: Prisma.SelectSubset<T, TaxPeriodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TaxPeriods and returns the data saved in the database.
   * @param {TaxPeriodCreateManyAndReturnArgs} args - Arguments to create many TaxPeriods.
   * @example
   * // Create many TaxPeriods
   * const taxPeriod = await prisma.taxPeriod.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TaxPeriods and only return the `id`
   * const taxPeriodWithIdOnly = await prisma.taxPeriod.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TaxPeriodCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TaxPeriodCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TaxPeriod.
   * @param {TaxPeriodDeleteArgs} args - Arguments to delete one TaxPeriod.
   * @example
   * // Delete one TaxPeriod
   * const TaxPeriod = await prisma.taxPeriod.delete({
   *   where: {
   *     // ... filter to delete one TaxPeriod
   *   }
   * })
   * 
   */
  delete<T extends TaxPeriodDeleteArgs>(args: Prisma.SelectSubset<T, TaxPeriodDeleteArgs<ExtArgs>>): Prisma.Prisma__TaxPeriodClient<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TaxPeriod.
   * @param {TaxPeriodUpdateArgs} args - Arguments to update one TaxPeriod.
   * @example
   * // Update one TaxPeriod
   * const taxPeriod = await prisma.taxPeriod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TaxPeriodUpdateArgs>(args: Prisma.SelectSubset<T, TaxPeriodUpdateArgs<ExtArgs>>): Prisma.Prisma__TaxPeriodClient<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TaxPeriods.
   * @param {TaxPeriodDeleteManyArgs} args - Arguments to filter TaxPeriods to delete.
   * @example
   * // Delete a few TaxPeriods
   * const { count } = await prisma.taxPeriod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TaxPeriodDeleteManyArgs>(args?: Prisma.SelectSubset<T, TaxPeriodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaxPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxPeriodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TaxPeriods
   * const taxPeriod = await prisma.taxPeriod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TaxPeriodUpdateManyArgs>(args: Prisma.SelectSubset<T, TaxPeriodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaxPeriods and returns the data updated in the database.
   * @param {TaxPeriodUpdateManyAndReturnArgs} args - Arguments to update many TaxPeriods.
   * @example
   * // Update many TaxPeriods
   * const taxPeriod = await prisma.taxPeriod.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TaxPeriods and only return the `id`
   * const taxPeriodWithIdOnly = await prisma.taxPeriod.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TaxPeriodUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TaxPeriodUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TaxPeriod.
   * @param {TaxPeriodUpsertArgs} args - Arguments to update or create a TaxPeriod.
   * @example
   * // Update or create a TaxPeriod
   * const taxPeriod = await prisma.taxPeriod.upsert({
   *   create: {
   *     // ... data to create a TaxPeriod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TaxPeriod we want to update
   *   }
   * })
   */
  upsert<T extends TaxPeriodUpsertArgs>(args: Prisma.SelectSubset<T, TaxPeriodUpsertArgs<ExtArgs>>): Prisma.Prisma__TaxPeriodClient<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TaxPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxPeriodCountArgs} args - Arguments to filter TaxPeriods to count.
   * @example
   * // Count the number of TaxPeriods
   * const count = await prisma.taxPeriod.count({
   *   where: {
   *     // ... the filter for the TaxPeriods we want to count
   *   }
   * })
  **/
  count<T extends TaxPeriodCountArgs>(
    args?: Prisma.Subset<T, TaxPeriodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TaxPeriodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TaxPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxPeriodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TaxPeriodAggregateArgs>(args: Prisma.Subset<T, TaxPeriodAggregateArgs>): Prisma.PrismaPromise<GetTaxPeriodAggregateType<T>>

  /**
   * Group by TaxPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxPeriodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TaxPeriodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TaxPeriodGroupByArgs['orderBy'] }
      : { orderBy?: TaxPeriodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TaxPeriodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTaxPeriodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TaxPeriod model
 */
readonly fields: TaxPeriodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TaxPeriod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TaxPeriodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  vatReturns<T extends Prisma.TaxPeriod$vatReturnsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaxPeriod$vatReturnsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TaxPeriod model
 */
export interface TaxPeriodFieldRefs {
  readonly id: Prisma.FieldRef<"TaxPeriod", 'String'>
  readonly startDate: Prisma.FieldRef<"TaxPeriod", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"TaxPeriod", 'DateTime'>
  readonly quarter: Prisma.FieldRef<"TaxPeriod", 'Int'>
  readonly year: Prisma.FieldRef<"TaxPeriod", 'Int'>
  readonly status: Prisma.FieldRef<"TaxPeriod", 'String'>
  readonly notes: Prisma.FieldRef<"TaxPeriod", 'String'>
  readonly createdAt: Prisma.FieldRef<"TaxPeriod", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TaxPeriod", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TaxPeriod findUnique
 */
export type TaxPeriodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxPeriodInclude<ExtArgs> | null
  /**
   * Filter, which TaxPeriod to fetch.
   */
  where: Prisma.TaxPeriodWhereUniqueInput
}

/**
 * TaxPeriod findUniqueOrThrow
 */
export type TaxPeriodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxPeriodInclude<ExtArgs> | null
  /**
   * Filter, which TaxPeriod to fetch.
   */
  where: Prisma.TaxPeriodWhereUniqueInput
}

/**
 * TaxPeriod findFirst
 */
export type TaxPeriodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxPeriodInclude<ExtArgs> | null
  /**
   * Filter, which TaxPeriod to fetch.
   */
  where?: Prisma.TaxPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxPeriods to fetch.
   */
  orderBy?: Prisma.TaxPeriodOrderByWithRelationInput | Prisma.TaxPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaxPeriods.
   */
  cursor?: Prisma.TaxPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaxPeriods.
   */
  distinct?: Prisma.TaxPeriodScalarFieldEnum | Prisma.TaxPeriodScalarFieldEnum[]
}

/**
 * TaxPeriod findFirstOrThrow
 */
export type TaxPeriodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxPeriodInclude<ExtArgs> | null
  /**
   * Filter, which TaxPeriod to fetch.
   */
  where?: Prisma.TaxPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxPeriods to fetch.
   */
  orderBy?: Prisma.TaxPeriodOrderByWithRelationInput | Prisma.TaxPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaxPeriods.
   */
  cursor?: Prisma.TaxPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaxPeriods.
   */
  distinct?: Prisma.TaxPeriodScalarFieldEnum | Prisma.TaxPeriodScalarFieldEnum[]
}

/**
 * TaxPeriod findMany
 */
export type TaxPeriodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxPeriodInclude<ExtArgs> | null
  /**
   * Filter, which TaxPeriods to fetch.
   */
  where?: Prisma.TaxPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxPeriods to fetch.
   */
  orderBy?: Prisma.TaxPeriodOrderByWithRelationInput | Prisma.TaxPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TaxPeriods.
   */
  cursor?: Prisma.TaxPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxPeriods.
   */
  skip?: number
  distinct?: Prisma.TaxPeriodScalarFieldEnum | Prisma.TaxPeriodScalarFieldEnum[]
}

/**
 * TaxPeriod create
 */
export type TaxPeriodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxPeriodInclude<ExtArgs> | null
  /**
   * The data needed to create a TaxPeriod.
   */
  data: Prisma.XOR<Prisma.TaxPeriodCreateInput, Prisma.TaxPeriodUncheckedCreateInput>
}

/**
 * TaxPeriod createMany
 */
export type TaxPeriodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TaxPeriods.
   */
  data: Prisma.TaxPeriodCreateManyInput | Prisma.TaxPeriodCreateManyInput[]
}

/**
 * TaxPeriod createManyAndReturn
 */
export type TaxPeriodCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * The data used to create many TaxPeriods.
   */
  data: Prisma.TaxPeriodCreateManyInput | Prisma.TaxPeriodCreateManyInput[]
}

/**
 * TaxPeriod update
 */
export type TaxPeriodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxPeriodInclude<ExtArgs> | null
  /**
   * The data needed to update a TaxPeriod.
   */
  data: Prisma.XOR<Prisma.TaxPeriodUpdateInput, Prisma.TaxPeriodUncheckedUpdateInput>
  /**
   * Choose, which TaxPeriod to update.
   */
  where: Prisma.TaxPeriodWhereUniqueInput
}

/**
 * TaxPeriod updateMany
 */
export type TaxPeriodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TaxPeriods.
   */
  data: Prisma.XOR<Prisma.TaxPeriodUpdateManyMutationInput, Prisma.TaxPeriodUncheckedUpdateManyInput>
  /**
   * Filter which TaxPeriods to update
   */
  where?: Prisma.TaxPeriodWhereInput
  /**
   * Limit how many TaxPeriods to update.
   */
  limit?: number
}

/**
 * TaxPeriod updateManyAndReturn
 */
export type TaxPeriodUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * The data used to update TaxPeriods.
   */
  data: Prisma.XOR<Prisma.TaxPeriodUpdateManyMutationInput, Prisma.TaxPeriodUncheckedUpdateManyInput>
  /**
   * Filter which TaxPeriods to update
   */
  where?: Prisma.TaxPeriodWhereInput
  /**
   * Limit how many TaxPeriods to update.
   */
  limit?: number
}

/**
 * TaxPeriod upsert
 */
export type TaxPeriodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxPeriodInclude<ExtArgs> | null
  /**
   * The filter to search for the TaxPeriod to update in case it exists.
   */
  where: Prisma.TaxPeriodWhereUniqueInput
  /**
   * In case the TaxPeriod found by the `where` argument doesn't exist, create a new TaxPeriod with this data.
   */
  create: Prisma.XOR<Prisma.TaxPeriodCreateInput, Prisma.TaxPeriodUncheckedCreateInput>
  /**
   * In case the TaxPeriod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TaxPeriodUpdateInput, Prisma.TaxPeriodUncheckedUpdateInput>
}

/**
 * TaxPeriod delete
 */
export type TaxPeriodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxPeriodInclude<ExtArgs> | null
  /**
   * Filter which TaxPeriod to delete.
   */
  where: Prisma.TaxPeriodWhereUniqueInput
}

/**
 * TaxPeriod deleteMany
 */
export type TaxPeriodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaxPeriods to delete
   */
  where?: Prisma.TaxPeriodWhereInput
  /**
   * Limit how many TaxPeriods to delete.
   */
  limit?: number
}

/**
 * TaxPeriod.vatReturns
 */
export type TaxPeriod$vatReturnsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
  where?: Prisma.VATReturnWhereInput
  orderBy?: Prisma.VATReturnOrderByWithRelationInput | Prisma.VATReturnOrderByWithRelationInput[]
  cursor?: Prisma.VATReturnWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VATReturnScalarFieldEnum | Prisma.VATReturnScalarFieldEnum[]
}

/**
 * TaxPeriod without action
 */
export type TaxPeriodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxPeriod
   */
  select?: Prisma.TaxPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxPeriod
   */
  omit?: Prisma.TaxPeriodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxPeriodInclude<ExtArgs> | null
}
