
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VATReturn` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VATReturn
 * 
 */
export type VATReturnModel = runtime.Types.Result.DefaultSelection<Prisma.$VATReturnPayload>

export type AggregateVATReturn = {
  _count: VATReturnCountAggregateOutputType | null
  _avg: VATReturnAvgAggregateOutputType | null
  _sum: VATReturnSumAggregateOutputType | null
  _min: VATReturnMinAggregateOutputType | null
  _max: VATReturnMaxAggregateOutputType | null
}

export type VATReturnAvgAggregateOutputType = {
  outputVAT: number | null
  inputVAT: number | null
  vatDue: number | null
}

export type VATReturnSumAggregateOutputType = {
  outputVAT: number | null
  inputVAT: number | null
  vatDue: number | null
}

export type VATReturnMinAggregateOutputType = {
  id: string | null
  taxPeriodId: string | null
  outputVAT: number | null
  inputVAT: number | null
  vatDue: number | null
  submittedAt: Date | null
  submittedBy: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VATReturnMaxAggregateOutputType = {
  id: string | null
  taxPeriodId: string | null
  outputVAT: number | null
  inputVAT: number | null
  vatDue: number | null
  submittedAt: Date | null
  submittedBy: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VATReturnCountAggregateOutputType = {
  id: number
  taxPeriodId: number
  outputVAT: number
  inputVAT: number
  vatDue: number
  submittedAt: number
  submittedBy: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type VATReturnAvgAggregateInputType = {
  outputVAT?: true
  inputVAT?: true
  vatDue?: true
}

export type VATReturnSumAggregateInputType = {
  outputVAT?: true
  inputVAT?: true
  vatDue?: true
}

export type VATReturnMinAggregateInputType = {
  id?: true
  taxPeriodId?: true
  outputVAT?: true
  inputVAT?: true
  vatDue?: true
  submittedAt?: true
  submittedBy?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type VATReturnMaxAggregateInputType = {
  id?: true
  taxPeriodId?: true
  outputVAT?: true
  inputVAT?: true
  vatDue?: true
  submittedAt?: true
  submittedBy?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type VATReturnCountAggregateInputType = {
  id?: true
  taxPeriodId?: true
  outputVAT?: true
  inputVAT?: true
  vatDue?: true
  submittedAt?: true
  submittedBy?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type VATReturnAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VATReturn to aggregate.
   */
  where?: Prisma.VATReturnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VATReturns to fetch.
   */
  orderBy?: Prisma.VATReturnOrderByWithRelationInput | Prisma.VATReturnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VATReturnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VATReturns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VATReturns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VATReturns
  **/
  _count?: true | VATReturnCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VATReturnAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VATReturnSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VATReturnMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VATReturnMaxAggregateInputType
}

export type GetVATReturnAggregateType<T extends VATReturnAggregateArgs> = {
      [P in keyof T & keyof AggregateVATReturn]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVATReturn[P]>
    : Prisma.GetScalarType<T[P], AggregateVATReturn[P]>
}




export type VATReturnGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VATReturnWhereInput
  orderBy?: Prisma.VATReturnOrderByWithAggregationInput | Prisma.VATReturnOrderByWithAggregationInput[]
  by: Prisma.VATReturnScalarFieldEnum[] | Prisma.VATReturnScalarFieldEnum
  having?: Prisma.VATReturnScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VATReturnCountAggregateInputType | true
  _avg?: VATReturnAvgAggregateInputType
  _sum?: VATReturnSumAggregateInputType
  _min?: VATReturnMinAggregateInputType
  _max?: VATReturnMaxAggregateInputType
}

export type VATReturnGroupByOutputType = {
  id: string
  taxPeriodId: string
  outputVAT: number
  inputVAT: number
  vatDue: number
  submittedAt: Date | null
  submittedBy: string | null
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: VATReturnCountAggregateOutputType | null
  _avg: VATReturnAvgAggregateOutputType | null
  _sum: VATReturnSumAggregateOutputType | null
  _min: VATReturnMinAggregateOutputType | null
  _max: VATReturnMaxAggregateOutputType | null
}

type GetVATReturnGroupByPayload<T extends VATReturnGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VATReturnGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VATReturnGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VATReturnGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VATReturnGroupByOutputType[P]>
      }
    >
  >



export type VATReturnWhereInput = {
  AND?: Prisma.VATReturnWhereInput | Prisma.VATReturnWhereInput[]
  OR?: Prisma.VATReturnWhereInput[]
  NOT?: Prisma.VATReturnWhereInput | Prisma.VATReturnWhereInput[]
  id?: Prisma.StringFilter<"VATReturn"> | string
  taxPeriodId?: Prisma.StringFilter<"VATReturn"> | string
  outputVAT?: Prisma.FloatFilter<"VATReturn"> | number
  inputVAT?: Prisma.FloatFilter<"VATReturn"> | number
  vatDue?: Prisma.FloatFilter<"VATReturn"> | number
  submittedAt?: Prisma.DateTimeNullableFilter<"VATReturn"> | Date | string | null
  submittedBy?: Prisma.StringNullableFilter<"VATReturn"> | string | null
  notes?: Prisma.StringNullableFilter<"VATReturn"> | string | null
  createdAt?: Prisma.DateTimeFilter<"VATReturn"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VATReturn"> | Date | string
  taxPeriod?: Prisma.XOR<Prisma.TaxPeriodScalarRelationFilter, Prisma.TaxPeriodWhereInput>
}

export type VATReturnOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  taxPeriodId?: Prisma.SortOrder
  outputVAT?: Prisma.SortOrder
  inputVAT?: Prisma.SortOrder
  vatDue?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  taxPeriod?: Prisma.TaxPeriodOrderByWithRelationInput
}

export type VATReturnWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VATReturnWhereInput | Prisma.VATReturnWhereInput[]
  OR?: Prisma.VATReturnWhereInput[]
  NOT?: Prisma.VATReturnWhereInput | Prisma.VATReturnWhereInput[]
  taxPeriodId?: Prisma.StringFilter<"VATReturn"> | string
  outputVAT?: Prisma.FloatFilter<"VATReturn"> | number
  inputVAT?: Prisma.FloatFilter<"VATReturn"> | number
  vatDue?: Prisma.FloatFilter<"VATReturn"> | number
  submittedAt?: Prisma.DateTimeNullableFilter<"VATReturn"> | Date | string | null
  submittedBy?: Prisma.StringNullableFilter<"VATReturn"> | string | null
  notes?: Prisma.StringNullableFilter<"VATReturn"> | string | null
  createdAt?: Prisma.DateTimeFilter<"VATReturn"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VATReturn"> | Date | string
  taxPeriod?: Prisma.XOR<Prisma.TaxPeriodScalarRelationFilter, Prisma.TaxPeriodWhereInput>
}, "id">

export type VATReturnOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  taxPeriodId?: Prisma.SortOrder
  outputVAT?: Prisma.SortOrder
  inputVAT?: Prisma.SortOrder
  vatDue?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.VATReturnCountOrderByAggregateInput
  _avg?: Prisma.VATReturnAvgOrderByAggregateInput
  _max?: Prisma.VATReturnMaxOrderByAggregateInput
  _min?: Prisma.VATReturnMinOrderByAggregateInput
  _sum?: Prisma.VATReturnSumOrderByAggregateInput
}

export type VATReturnScalarWhereWithAggregatesInput = {
  AND?: Prisma.VATReturnScalarWhereWithAggregatesInput | Prisma.VATReturnScalarWhereWithAggregatesInput[]
  OR?: Prisma.VATReturnScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VATReturnScalarWhereWithAggregatesInput | Prisma.VATReturnScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VATReturn"> | string
  taxPeriodId?: Prisma.StringWithAggregatesFilter<"VATReturn"> | string
  outputVAT?: Prisma.FloatWithAggregatesFilter<"VATReturn"> | number
  inputVAT?: Prisma.FloatWithAggregatesFilter<"VATReturn"> | number
  vatDue?: Prisma.FloatWithAggregatesFilter<"VATReturn"> | number
  submittedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"VATReturn"> | Date | string | null
  submittedBy?: Prisma.StringNullableWithAggregatesFilter<"VATReturn"> | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"VATReturn"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VATReturn"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"VATReturn"> | Date | string
}

export type VATReturnCreateInput = {
  id?: string
  outputVAT?: number
  inputVAT?: number
  vatDue?: number
  submittedAt?: Date | string | null
  submittedBy?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  taxPeriod: Prisma.TaxPeriodCreateNestedOneWithoutVatReturnsInput
}

export type VATReturnUncheckedCreateInput = {
  id?: string
  taxPeriodId: string
  outputVAT?: number
  inputVAT?: number
  vatDue?: number
  submittedAt?: Date | string | null
  submittedBy?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VATReturnUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  inputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  vatDue?: Prisma.FloatFieldUpdateOperationsInput | number
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxPeriod?: Prisma.TaxPeriodUpdateOneRequiredWithoutVatReturnsNestedInput
}

export type VATReturnUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taxPeriodId?: Prisma.StringFieldUpdateOperationsInput | string
  outputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  inputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  vatDue?: Prisma.FloatFieldUpdateOperationsInput | number
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VATReturnCreateManyInput = {
  id?: string
  taxPeriodId: string
  outputVAT?: number
  inputVAT?: number
  vatDue?: number
  submittedAt?: Date | string | null
  submittedBy?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VATReturnUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  inputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  vatDue?: Prisma.FloatFieldUpdateOperationsInput | number
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VATReturnUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taxPeriodId?: Prisma.StringFieldUpdateOperationsInput | string
  outputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  inputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  vatDue?: Prisma.FloatFieldUpdateOperationsInput | number
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VATReturnListRelationFilter = {
  every?: Prisma.VATReturnWhereInput
  some?: Prisma.VATReturnWhereInput
  none?: Prisma.VATReturnWhereInput
}

export type VATReturnOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VATReturnCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taxPeriodId?: Prisma.SortOrder
  outputVAT?: Prisma.SortOrder
  inputVAT?: Prisma.SortOrder
  vatDue?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VATReturnAvgOrderByAggregateInput = {
  outputVAT?: Prisma.SortOrder
  inputVAT?: Prisma.SortOrder
  vatDue?: Prisma.SortOrder
}

export type VATReturnMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taxPeriodId?: Prisma.SortOrder
  outputVAT?: Prisma.SortOrder
  inputVAT?: Prisma.SortOrder
  vatDue?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VATReturnMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taxPeriodId?: Prisma.SortOrder
  outputVAT?: Prisma.SortOrder
  inputVAT?: Prisma.SortOrder
  vatDue?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VATReturnSumOrderByAggregateInput = {
  outputVAT?: Prisma.SortOrder
  inputVAT?: Prisma.SortOrder
  vatDue?: Prisma.SortOrder
}

export type VATReturnCreateNestedManyWithoutTaxPeriodInput = {
  create?: Prisma.XOR<Prisma.VATReturnCreateWithoutTaxPeriodInput, Prisma.VATReturnUncheckedCreateWithoutTaxPeriodInput> | Prisma.VATReturnCreateWithoutTaxPeriodInput[] | Prisma.VATReturnUncheckedCreateWithoutTaxPeriodInput[]
  connectOrCreate?: Prisma.VATReturnCreateOrConnectWithoutTaxPeriodInput | Prisma.VATReturnCreateOrConnectWithoutTaxPeriodInput[]
  createMany?: Prisma.VATReturnCreateManyTaxPeriodInputEnvelope
  connect?: Prisma.VATReturnWhereUniqueInput | Prisma.VATReturnWhereUniqueInput[]
}

export type VATReturnUncheckedCreateNestedManyWithoutTaxPeriodInput = {
  create?: Prisma.XOR<Prisma.VATReturnCreateWithoutTaxPeriodInput, Prisma.VATReturnUncheckedCreateWithoutTaxPeriodInput> | Prisma.VATReturnCreateWithoutTaxPeriodInput[] | Prisma.VATReturnUncheckedCreateWithoutTaxPeriodInput[]
  connectOrCreate?: Prisma.VATReturnCreateOrConnectWithoutTaxPeriodInput | Prisma.VATReturnCreateOrConnectWithoutTaxPeriodInput[]
  createMany?: Prisma.VATReturnCreateManyTaxPeriodInputEnvelope
  connect?: Prisma.VATReturnWhereUniqueInput | Prisma.VATReturnWhereUniqueInput[]
}

export type VATReturnUpdateManyWithoutTaxPeriodNestedInput = {
  create?: Prisma.XOR<Prisma.VATReturnCreateWithoutTaxPeriodInput, Prisma.VATReturnUncheckedCreateWithoutTaxPeriodInput> | Prisma.VATReturnCreateWithoutTaxPeriodInput[] | Prisma.VATReturnUncheckedCreateWithoutTaxPeriodInput[]
  connectOrCreate?: Prisma.VATReturnCreateOrConnectWithoutTaxPeriodInput | Prisma.VATReturnCreateOrConnectWithoutTaxPeriodInput[]
  upsert?: Prisma.VATReturnUpsertWithWhereUniqueWithoutTaxPeriodInput | Prisma.VATReturnUpsertWithWhereUniqueWithoutTaxPeriodInput[]
  createMany?: Prisma.VATReturnCreateManyTaxPeriodInputEnvelope
  set?: Prisma.VATReturnWhereUniqueInput | Prisma.VATReturnWhereUniqueInput[]
  disconnect?: Prisma.VATReturnWhereUniqueInput | Prisma.VATReturnWhereUniqueInput[]
  delete?: Prisma.VATReturnWhereUniqueInput | Prisma.VATReturnWhereUniqueInput[]
  connect?: Prisma.VATReturnWhereUniqueInput | Prisma.VATReturnWhereUniqueInput[]
  update?: Prisma.VATReturnUpdateWithWhereUniqueWithoutTaxPeriodInput | Prisma.VATReturnUpdateWithWhereUniqueWithoutTaxPeriodInput[]
  updateMany?: Prisma.VATReturnUpdateManyWithWhereWithoutTaxPeriodInput | Prisma.VATReturnUpdateManyWithWhereWithoutTaxPeriodInput[]
  deleteMany?: Prisma.VATReturnScalarWhereInput | Prisma.VATReturnScalarWhereInput[]
}

export type VATReturnUncheckedUpdateManyWithoutTaxPeriodNestedInput = {
  create?: Prisma.XOR<Prisma.VATReturnCreateWithoutTaxPeriodInput, Prisma.VATReturnUncheckedCreateWithoutTaxPeriodInput> | Prisma.VATReturnCreateWithoutTaxPeriodInput[] | Prisma.VATReturnUncheckedCreateWithoutTaxPeriodInput[]
  connectOrCreate?: Prisma.VATReturnCreateOrConnectWithoutTaxPeriodInput | Prisma.VATReturnCreateOrConnectWithoutTaxPeriodInput[]
  upsert?: Prisma.VATReturnUpsertWithWhereUniqueWithoutTaxPeriodInput | Prisma.VATReturnUpsertWithWhereUniqueWithoutTaxPeriodInput[]
  createMany?: Prisma.VATReturnCreateManyTaxPeriodInputEnvelope
  set?: Prisma.VATReturnWhereUniqueInput | Prisma.VATReturnWhereUniqueInput[]
  disconnect?: Prisma.VATReturnWhereUniqueInput | Prisma.VATReturnWhereUniqueInput[]
  delete?: Prisma.VATReturnWhereUniqueInput | Prisma.VATReturnWhereUniqueInput[]
  connect?: Prisma.VATReturnWhereUniqueInput | Prisma.VATReturnWhereUniqueInput[]
  update?: Prisma.VATReturnUpdateWithWhereUniqueWithoutTaxPeriodInput | Prisma.VATReturnUpdateWithWhereUniqueWithoutTaxPeriodInput[]
  updateMany?: Prisma.VATReturnUpdateManyWithWhereWithoutTaxPeriodInput | Prisma.VATReturnUpdateManyWithWhereWithoutTaxPeriodInput[]
  deleteMany?: Prisma.VATReturnScalarWhereInput | Prisma.VATReturnScalarWhereInput[]
}

export type VATReturnCreateWithoutTaxPeriodInput = {
  id?: string
  outputVAT?: number
  inputVAT?: number
  vatDue?: number
  submittedAt?: Date | string | null
  submittedBy?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VATReturnUncheckedCreateWithoutTaxPeriodInput = {
  id?: string
  outputVAT?: number
  inputVAT?: number
  vatDue?: number
  submittedAt?: Date | string | null
  submittedBy?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VATReturnCreateOrConnectWithoutTaxPeriodInput = {
  where: Prisma.VATReturnWhereUniqueInput
  create: Prisma.XOR<Prisma.VATReturnCreateWithoutTaxPeriodInput, Prisma.VATReturnUncheckedCreateWithoutTaxPeriodInput>
}

export type VATReturnCreateManyTaxPeriodInputEnvelope = {
  data: Prisma.VATReturnCreateManyTaxPeriodInput | Prisma.VATReturnCreateManyTaxPeriodInput[]
}

export type VATReturnUpsertWithWhereUniqueWithoutTaxPeriodInput = {
  where: Prisma.VATReturnWhereUniqueInput
  update: Prisma.XOR<Prisma.VATReturnUpdateWithoutTaxPeriodInput, Prisma.VATReturnUncheckedUpdateWithoutTaxPeriodInput>
  create: Prisma.XOR<Prisma.VATReturnCreateWithoutTaxPeriodInput, Prisma.VATReturnUncheckedCreateWithoutTaxPeriodInput>
}

export type VATReturnUpdateWithWhereUniqueWithoutTaxPeriodInput = {
  where: Prisma.VATReturnWhereUniqueInput
  data: Prisma.XOR<Prisma.VATReturnUpdateWithoutTaxPeriodInput, Prisma.VATReturnUncheckedUpdateWithoutTaxPeriodInput>
}

export type VATReturnUpdateManyWithWhereWithoutTaxPeriodInput = {
  where: Prisma.VATReturnScalarWhereInput
  data: Prisma.XOR<Prisma.VATReturnUpdateManyMutationInput, Prisma.VATReturnUncheckedUpdateManyWithoutTaxPeriodInput>
}

export type VATReturnScalarWhereInput = {
  AND?: Prisma.VATReturnScalarWhereInput | Prisma.VATReturnScalarWhereInput[]
  OR?: Prisma.VATReturnScalarWhereInput[]
  NOT?: Prisma.VATReturnScalarWhereInput | Prisma.VATReturnScalarWhereInput[]
  id?: Prisma.StringFilter<"VATReturn"> | string
  taxPeriodId?: Prisma.StringFilter<"VATReturn"> | string
  outputVAT?: Prisma.FloatFilter<"VATReturn"> | number
  inputVAT?: Prisma.FloatFilter<"VATReturn"> | number
  vatDue?: Prisma.FloatFilter<"VATReturn"> | number
  submittedAt?: Prisma.DateTimeNullableFilter<"VATReturn"> | Date | string | null
  submittedBy?: Prisma.StringNullableFilter<"VATReturn"> | string | null
  notes?: Prisma.StringNullableFilter<"VATReturn"> | string | null
  createdAt?: Prisma.DateTimeFilter<"VATReturn"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VATReturn"> | Date | string
}

export type VATReturnCreateManyTaxPeriodInput = {
  id?: string
  outputVAT?: number
  inputVAT?: number
  vatDue?: number
  submittedAt?: Date | string | null
  submittedBy?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VATReturnUpdateWithoutTaxPeriodInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  inputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  vatDue?: Prisma.FloatFieldUpdateOperationsInput | number
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VATReturnUncheckedUpdateWithoutTaxPeriodInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  inputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  vatDue?: Prisma.FloatFieldUpdateOperationsInput | number
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VATReturnUncheckedUpdateManyWithoutTaxPeriodInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  inputVAT?: Prisma.FloatFieldUpdateOperationsInput | number
  vatDue?: Prisma.FloatFieldUpdateOperationsInput | number
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type VATReturnSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taxPeriodId?: boolean
  outputVAT?: boolean
  inputVAT?: boolean
  vatDue?: boolean
  submittedAt?: boolean
  submittedBy?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  taxPeriod?: boolean | Prisma.TaxPeriodDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vATReturn"]>

export type VATReturnSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taxPeriodId?: boolean
  outputVAT?: boolean
  inputVAT?: boolean
  vatDue?: boolean
  submittedAt?: boolean
  submittedBy?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  taxPeriod?: boolean | Prisma.TaxPeriodDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vATReturn"]>

export type VATReturnSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taxPeriodId?: boolean
  outputVAT?: boolean
  inputVAT?: boolean
  vatDue?: boolean
  submittedAt?: boolean
  submittedBy?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  taxPeriod?: boolean | Prisma.TaxPeriodDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vATReturn"]>

export type VATReturnSelectScalar = {
  id?: boolean
  taxPeriodId?: boolean
  outputVAT?: boolean
  inputVAT?: boolean
  vatDue?: boolean
  submittedAt?: boolean
  submittedBy?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type VATReturnOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "taxPeriodId" | "outputVAT" | "inputVAT" | "vatDue" | "submittedAt" | "submittedBy" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["vATReturn"]>
export type VATReturnInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  taxPeriod?: boolean | Prisma.TaxPeriodDefaultArgs<ExtArgs>
}
export type VATReturnIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  taxPeriod?: boolean | Prisma.TaxPeriodDefaultArgs<ExtArgs>
}
export type VATReturnIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  taxPeriod?: boolean | Prisma.TaxPeriodDefaultArgs<ExtArgs>
}

export type $VATReturnPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VATReturn"
  objects: {
    taxPeriod: Prisma.$TaxPeriodPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    taxPeriodId: string
    outputVAT: number
    inputVAT: number
    vatDue: number
    submittedAt: Date | null
    submittedBy: string | null
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["vATReturn"]>
  composites: {}
}

export type VATReturnGetPayload<S extends boolean | null | undefined | VATReturnDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VATReturnPayload, S>

export type VATReturnCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VATReturnFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VATReturnCountAggregateInputType | true
  }

export interface VATReturnDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VATReturn'], meta: { name: 'VATReturn' } }
  /**
   * Find zero or one VATReturn that matches the filter.
   * @param {VATReturnFindUniqueArgs} args - Arguments to find a VATReturn
   * @example
   * // Get one VATReturn
   * const vATReturn = await prisma.vATReturn.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VATReturnFindUniqueArgs>(args: Prisma.SelectSubset<T, VATReturnFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VATReturnClient<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VATReturn that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VATReturnFindUniqueOrThrowArgs} args - Arguments to find a VATReturn
   * @example
   * // Get one VATReturn
   * const vATReturn = await prisma.vATReturn.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VATReturnFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VATReturnFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VATReturnClient<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VATReturn that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATReturnFindFirstArgs} args - Arguments to find a VATReturn
   * @example
   * // Get one VATReturn
   * const vATReturn = await prisma.vATReturn.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VATReturnFindFirstArgs>(args?: Prisma.SelectSubset<T, VATReturnFindFirstArgs<ExtArgs>>): Prisma.Prisma__VATReturnClient<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VATReturn that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATReturnFindFirstOrThrowArgs} args - Arguments to find a VATReturn
   * @example
   * // Get one VATReturn
   * const vATReturn = await prisma.vATReturn.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VATReturnFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VATReturnFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VATReturnClient<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VATReturns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATReturnFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VATReturns
   * const vATReturns = await prisma.vATReturn.findMany()
   * 
   * // Get first 10 VATReturns
   * const vATReturns = await prisma.vATReturn.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vATReturnWithIdOnly = await prisma.vATReturn.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VATReturnFindManyArgs>(args?: Prisma.SelectSubset<T, VATReturnFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VATReturn.
   * @param {VATReturnCreateArgs} args - Arguments to create a VATReturn.
   * @example
   * // Create one VATReturn
   * const VATReturn = await prisma.vATReturn.create({
   *   data: {
   *     // ... data to create a VATReturn
   *   }
   * })
   * 
   */
  create<T extends VATReturnCreateArgs>(args: Prisma.SelectSubset<T, VATReturnCreateArgs<ExtArgs>>): Prisma.Prisma__VATReturnClient<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VATReturns.
   * @param {VATReturnCreateManyArgs} args - Arguments to create many VATReturns.
   * @example
   * // Create many VATReturns
   * const vATReturn = await prisma.vATReturn.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VATReturnCreateManyArgs>(args?: Prisma.SelectSubset<T, VATReturnCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VATReturns and returns the data saved in the database.
   * @param {VATReturnCreateManyAndReturnArgs} args - Arguments to create many VATReturns.
   * @example
   * // Create many VATReturns
   * const vATReturn = await prisma.vATReturn.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VATReturns and only return the `id`
   * const vATReturnWithIdOnly = await prisma.vATReturn.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VATReturnCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VATReturnCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VATReturn.
   * @param {VATReturnDeleteArgs} args - Arguments to delete one VATReturn.
   * @example
   * // Delete one VATReturn
   * const VATReturn = await prisma.vATReturn.delete({
   *   where: {
   *     // ... filter to delete one VATReturn
   *   }
   * })
   * 
   */
  delete<T extends VATReturnDeleteArgs>(args: Prisma.SelectSubset<T, VATReturnDeleteArgs<ExtArgs>>): Prisma.Prisma__VATReturnClient<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VATReturn.
   * @param {VATReturnUpdateArgs} args - Arguments to update one VATReturn.
   * @example
   * // Update one VATReturn
   * const vATReturn = await prisma.vATReturn.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VATReturnUpdateArgs>(args: Prisma.SelectSubset<T, VATReturnUpdateArgs<ExtArgs>>): Prisma.Prisma__VATReturnClient<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VATReturns.
   * @param {VATReturnDeleteManyArgs} args - Arguments to filter VATReturns to delete.
   * @example
   * // Delete a few VATReturns
   * const { count } = await prisma.vATReturn.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VATReturnDeleteManyArgs>(args?: Prisma.SelectSubset<T, VATReturnDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VATReturns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATReturnUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VATReturns
   * const vATReturn = await prisma.vATReturn.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VATReturnUpdateManyArgs>(args: Prisma.SelectSubset<T, VATReturnUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VATReturns and returns the data updated in the database.
   * @param {VATReturnUpdateManyAndReturnArgs} args - Arguments to update many VATReturns.
   * @example
   * // Update many VATReturns
   * const vATReturn = await prisma.vATReturn.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VATReturns and only return the `id`
   * const vATReturnWithIdOnly = await prisma.vATReturn.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VATReturnUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VATReturnUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VATReturn.
   * @param {VATReturnUpsertArgs} args - Arguments to update or create a VATReturn.
   * @example
   * // Update or create a VATReturn
   * const vATReturn = await prisma.vATReturn.upsert({
   *   create: {
   *     // ... data to create a VATReturn
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VATReturn we want to update
   *   }
   * })
   */
  upsert<T extends VATReturnUpsertArgs>(args: Prisma.SelectSubset<T, VATReturnUpsertArgs<ExtArgs>>): Prisma.Prisma__VATReturnClient<runtime.Types.Result.GetResult<Prisma.$VATReturnPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VATReturns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATReturnCountArgs} args - Arguments to filter VATReturns to count.
   * @example
   * // Count the number of VATReturns
   * const count = await prisma.vATReturn.count({
   *   where: {
   *     // ... the filter for the VATReturns we want to count
   *   }
   * })
  **/
  count<T extends VATReturnCountArgs>(
    args?: Prisma.Subset<T, VATReturnCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VATReturnCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VATReturn.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATReturnAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VATReturnAggregateArgs>(args: Prisma.Subset<T, VATReturnAggregateArgs>): Prisma.PrismaPromise<GetVATReturnAggregateType<T>>

  /**
   * Group by VATReturn.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATReturnGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VATReturnGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VATReturnGroupByArgs['orderBy'] }
      : { orderBy?: VATReturnGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VATReturnGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVATReturnGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VATReturn model
 */
readonly fields: VATReturnFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VATReturn.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VATReturnClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  taxPeriod<T extends Prisma.TaxPeriodDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaxPeriodDefaultArgs<ExtArgs>>): Prisma.Prisma__TaxPeriodClient<runtime.Types.Result.GetResult<Prisma.$TaxPeriodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VATReturn model
 */
export interface VATReturnFieldRefs {
  readonly id: Prisma.FieldRef<"VATReturn", 'String'>
  readonly taxPeriodId: Prisma.FieldRef<"VATReturn", 'String'>
  readonly outputVAT: Prisma.FieldRef<"VATReturn", 'Float'>
  readonly inputVAT: Prisma.FieldRef<"VATReturn", 'Float'>
  readonly vatDue: Prisma.FieldRef<"VATReturn", 'Float'>
  readonly submittedAt: Prisma.FieldRef<"VATReturn", 'DateTime'>
  readonly submittedBy: Prisma.FieldRef<"VATReturn", 'String'>
  readonly notes: Prisma.FieldRef<"VATReturn", 'String'>
  readonly createdAt: Prisma.FieldRef<"VATReturn", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"VATReturn", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VATReturn findUnique
 */
export type VATReturnFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
  /**
   * Filter, which VATReturn to fetch.
   */
  where: Prisma.VATReturnWhereUniqueInput
}

/**
 * VATReturn findUniqueOrThrow
 */
export type VATReturnFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
  /**
   * Filter, which VATReturn to fetch.
   */
  where: Prisma.VATReturnWhereUniqueInput
}

/**
 * VATReturn findFirst
 */
export type VATReturnFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
  /**
   * Filter, which VATReturn to fetch.
   */
  where?: Prisma.VATReturnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VATReturns to fetch.
   */
  orderBy?: Prisma.VATReturnOrderByWithRelationInput | Prisma.VATReturnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VATReturns.
   */
  cursor?: Prisma.VATReturnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VATReturns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VATReturns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VATReturns.
   */
  distinct?: Prisma.VATReturnScalarFieldEnum | Prisma.VATReturnScalarFieldEnum[]
}

/**
 * VATReturn findFirstOrThrow
 */
export type VATReturnFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
  /**
   * Filter, which VATReturn to fetch.
   */
  where?: Prisma.VATReturnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VATReturns to fetch.
   */
  orderBy?: Prisma.VATReturnOrderByWithRelationInput | Prisma.VATReturnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VATReturns.
   */
  cursor?: Prisma.VATReturnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VATReturns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VATReturns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VATReturns.
   */
  distinct?: Prisma.VATReturnScalarFieldEnum | Prisma.VATReturnScalarFieldEnum[]
}

/**
 * VATReturn findMany
 */
export type VATReturnFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
  /**
   * Filter, which VATReturns to fetch.
   */
  where?: Prisma.VATReturnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VATReturns to fetch.
   */
  orderBy?: Prisma.VATReturnOrderByWithRelationInput | Prisma.VATReturnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VATReturns.
   */
  cursor?: Prisma.VATReturnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VATReturns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VATReturns.
   */
  skip?: number
  distinct?: Prisma.VATReturnScalarFieldEnum | Prisma.VATReturnScalarFieldEnum[]
}

/**
 * VATReturn create
 */
export type VATReturnCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
  /**
   * The data needed to create a VATReturn.
   */
  data: Prisma.XOR<Prisma.VATReturnCreateInput, Prisma.VATReturnUncheckedCreateInput>
}

/**
 * VATReturn createMany
 */
export type VATReturnCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VATReturns.
   */
  data: Prisma.VATReturnCreateManyInput | Prisma.VATReturnCreateManyInput[]
}

/**
 * VATReturn createManyAndReturn
 */
export type VATReturnCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * The data used to create many VATReturns.
   */
  data: Prisma.VATReturnCreateManyInput | Prisma.VATReturnCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VATReturn update
 */
export type VATReturnUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
  /**
   * The data needed to update a VATReturn.
   */
  data: Prisma.XOR<Prisma.VATReturnUpdateInput, Prisma.VATReturnUncheckedUpdateInput>
  /**
   * Choose, which VATReturn to update.
   */
  where: Prisma.VATReturnWhereUniqueInput
}

/**
 * VATReturn updateMany
 */
export type VATReturnUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VATReturns.
   */
  data: Prisma.XOR<Prisma.VATReturnUpdateManyMutationInput, Prisma.VATReturnUncheckedUpdateManyInput>
  /**
   * Filter which VATReturns to update
   */
  where?: Prisma.VATReturnWhereInput
  /**
   * Limit how many VATReturns to update.
   */
  limit?: number
}

/**
 * VATReturn updateManyAndReturn
 */
export type VATReturnUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * The data used to update VATReturns.
   */
  data: Prisma.XOR<Prisma.VATReturnUpdateManyMutationInput, Prisma.VATReturnUncheckedUpdateManyInput>
  /**
   * Filter which VATReturns to update
   */
  where?: Prisma.VATReturnWhereInput
  /**
   * Limit how many VATReturns to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VATReturn upsert
 */
export type VATReturnUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
  /**
   * The filter to search for the VATReturn to update in case it exists.
   */
  where: Prisma.VATReturnWhereUniqueInput
  /**
   * In case the VATReturn found by the `where` argument doesn't exist, create a new VATReturn with this data.
   */
  create: Prisma.XOR<Prisma.VATReturnCreateInput, Prisma.VATReturnUncheckedCreateInput>
  /**
   * In case the VATReturn was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VATReturnUpdateInput, Prisma.VATReturnUncheckedUpdateInput>
}

/**
 * VATReturn delete
 */
export type VATReturnDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
  /**
   * Filter which VATReturn to delete.
   */
  where: Prisma.VATReturnWhereUniqueInput
}

/**
 * VATReturn deleteMany
 */
export type VATReturnDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VATReturns to delete
   */
  where?: Prisma.VATReturnWhereInput
  /**
   * Limit how many VATReturns to delete.
   */
  limit?: number
}

/**
 * VATReturn without action
 */
export type VATReturnDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATReturn
   */
  select?: Prisma.VATReturnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATReturn
   */
  omit?: Prisma.VATReturnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VATReturnInclude<ExtArgs> | null
}
