
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VATRate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VATRate
 * 
 */
export type VATRateModel = runtime.Types.Result.DefaultSelection<Prisma.$VATRatePayload>

export type AggregateVATRate = {
  _count: VATRateCountAggregateOutputType | null
  _avg: VATRateAvgAggregateOutputType | null
  _sum: VATRateSumAggregateOutputType | null
  _min: VATRateMinAggregateOutputType | null
  _max: VATRateMaxAggregateOutputType | null
}

export type VATRateAvgAggregateOutputType = {
  rate: number | null
}

export type VATRateSumAggregateOutputType = {
  rate: number | null
}

export type VATRateMinAggregateOutputType = {
  id: string | null
  rate: number | null
  name: string | null
  description: string | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VATRateMaxAggregateOutputType = {
  id: string | null
  rate: number | null
  name: string | null
  description: string | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VATRateCountAggregateOutputType = {
  id: number
  rate: number
  name: number
  description: number
  active: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type VATRateAvgAggregateInputType = {
  rate?: true
}

export type VATRateSumAggregateInputType = {
  rate?: true
}

export type VATRateMinAggregateInputType = {
  id?: true
  rate?: true
  name?: true
  description?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type VATRateMaxAggregateInputType = {
  id?: true
  rate?: true
  name?: true
  description?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type VATRateCountAggregateInputType = {
  id?: true
  rate?: true
  name?: true
  description?: true
  active?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type VATRateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VATRate to aggregate.
   */
  where?: Prisma.VATRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VATRates to fetch.
   */
  orderBy?: Prisma.VATRateOrderByWithRelationInput | Prisma.VATRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VATRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VATRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VATRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VATRates
  **/
  _count?: true | VATRateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VATRateAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VATRateSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VATRateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VATRateMaxAggregateInputType
}

export type GetVATRateAggregateType<T extends VATRateAggregateArgs> = {
      [P in keyof T & keyof AggregateVATRate]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVATRate[P]>
    : Prisma.GetScalarType<T[P], AggregateVATRate[P]>
}




export type VATRateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VATRateWhereInput
  orderBy?: Prisma.VATRateOrderByWithAggregationInput | Prisma.VATRateOrderByWithAggregationInput[]
  by: Prisma.VATRateScalarFieldEnum[] | Prisma.VATRateScalarFieldEnum
  having?: Prisma.VATRateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VATRateCountAggregateInputType | true
  _avg?: VATRateAvgAggregateInputType
  _sum?: VATRateSumAggregateInputType
  _min?: VATRateMinAggregateInputType
  _max?: VATRateMaxAggregateInputType
}

export type VATRateGroupByOutputType = {
  id: string
  rate: number
  name: string
  description: string | null
  active: boolean
  createdAt: Date
  updatedAt: Date
  _count: VATRateCountAggregateOutputType | null
  _avg: VATRateAvgAggregateOutputType | null
  _sum: VATRateSumAggregateOutputType | null
  _min: VATRateMinAggregateOutputType | null
  _max: VATRateMaxAggregateOutputType | null
}

type GetVATRateGroupByPayload<T extends VATRateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VATRateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VATRateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VATRateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VATRateGroupByOutputType[P]>
      }
    >
  >



export type VATRateWhereInput = {
  AND?: Prisma.VATRateWhereInput | Prisma.VATRateWhereInput[]
  OR?: Prisma.VATRateWhereInput[]
  NOT?: Prisma.VATRateWhereInput | Prisma.VATRateWhereInput[]
  id?: Prisma.StringFilter<"VATRate"> | string
  rate?: Prisma.FloatFilter<"VATRate"> | number
  name?: Prisma.StringFilter<"VATRate"> | string
  description?: Prisma.StringNullableFilter<"VATRate"> | string | null
  active?: Prisma.BoolFilter<"VATRate"> | boolean
  createdAt?: Prisma.DateTimeFilter<"VATRate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VATRate"> | Date | string
}

export type VATRateOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VATRateWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VATRateWhereInput | Prisma.VATRateWhereInput[]
  OR?: Prisma.VATRateWhereInput[]
  NOT?: Prisma.VATRateWhereInput | Prisma.VATRateWhereInput[]
  rate?: Prisma.FloatFilter<"VATRate"> | number
  name?: Prisma.StringFilter<"VATRate"> | string
  description?: Prisma.StringNullableFilter<"VATRate"> | string | null
  active?: Prisma.BoolFilter<"VATRate"> | boolean
  createdAt?: Prisma.DateTimeFilter<"VATRate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VATRate"> | Date | string
}, "id">

export type VATRateOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.VATRateCountOrderByAggregateInput
  _avg?: Prisma.VATRateAvgOrderByAggregateInput
  _max?: Prisma.VATRateMaxOrderByAggregateInput
  _min?: Prisma.VATRateMinOrderByAggregateInput
  _sum?: Prisma.VATRateSumOrderByAggregateInput
}

export type VATRateScalarWhereWithAggregatesInput = {
  AND?: Prisma.VATRateScalarWhereWithAggregatesInput | Prisma.VATRateScalarWhereWithAggregatesInput[]
  OR?: Prisma.VATRateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VATRateScalarWhereWithAggregatesInput | Prisma.VATRateScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VATRate"> | string
  rate?: Prisma.FloatWithAggregatesFilter<"VATRate"> | number
  name?: Prisma.StringWithAggregatesFilter<"VATRate"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"VATRate"> | string | null
  active?: Prisma.BoolWithAggregatesFilter<"VATRate"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VATRate"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"VATRate"> | Date | string
}

export type VATRateCreateInput = {
  id?: string
  rate: number
  name: string
  description?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VATRateUncheckedCreateInput = {
  id?: string
  rate: number
  name: string
  description?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VATRateUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rate?: Prisma.FloatFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VATRateUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rate?: Prisma.FloatFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VATRateCreateManyInput = {
  id?: string
  rate: number
  name: string
  description?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VATRateUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rate?: Prisma.FloatFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VATRateUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rate?: Prisma.FloatFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VATRateCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VATRateAvgOrderByAggregateInput = {
  rate?: Prisma.SortOrder
}

export type VATRateMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VATRateMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VATRateSumOrderByAggregateInput = {
  rate?: Prisma.SortOrder
}



export type VATRateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rate?: boolean
  name?: boolean
  description?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["vATRate"]>

export type VATRateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rate?: boolean
  name?: boolean
  description?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["vATRate"]>

export type VATRateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rate?: boolean
  name?: boolean
  description?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["vATRate"]>

export type VATRateSelectScalar = {
  id?: boolean
  rate?: boolean
  name?: boolean
  description?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type VATRateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "rate" | "name" | "description" | "active" | "createdAt" | "updatedAt", ExtArgs["result"]["vATRate"]>

export type $VATRatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VATRate"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    rate: number
    name: string
    description: string | null
    active: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["vATRate"]>
  composites: {}
}

export type VATRateGetPayload<S extends boolean | null | undefined | VATRateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VATRatePayload, S>

export type VATRateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VATRateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VATRateCountAggregateInputType | true
  }

export interface VATRateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VATRate'], meta: { name: 'VATRate' } }
  /**
   * Find zero or one VATRate that matches the filter.
   * @param {VATRateFindUniqueArgs} args - Arguments to find a VATRate
   * @example
   * // Get one VATRate
   * const vATRate = await prisma.vATRate.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VATRateFindUniqueArgs>(args: Prisma.SelectSubset<T, VATRateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VATRateClient<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VATRate that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VATRateFindUniqueOrThrowArgs} args - Arguments to find a VATRate
   * @example
   * // Get one VATRate
   * const vATRate = await prisma.vATRate.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VATRateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VATRateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VATRateClient<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VATRate that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATRateFindFirstArgs} args - Arguments to find a VATRate
   * @example
   * // Get one VATRate
   * const vATRate = await prisma.vATRate.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VATRateFindFirstArgs>(args?: Prisma.SelectSubset<T, VATRateFindFirstArgs<ExtArgs>>): Prisma.Prisma__VATRateClient<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VATRate that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATRateFindFirstOrThrowArgs} args - Arguments to find a VATRate
   * @example
   * // Get one VATRate
   * const vATRate = await prisma.vATRate.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VATRateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VATRateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VATRateClient<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VATRates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATRateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VATRates
   * const vATRates = await prisma.vATRate.findMany()
   * 
   * // Get first 10 VATRates
   * const vATRates = await prisma.vATRate.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vATRateWithIdOnly = await prisma.vATRate.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VATRateFindManyArgs>(args?: Prisma.SelectSubset<T, VATRateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VATRate.
   * @param {VATRateCreateArgs} args - Arguments to create a VATRate.
   * @example
   * // Create one VATRate
   * const VATRate = await prisma.vATRate.create({
   *   data: {
   *     // ... data to create a VATRate
   *   }
   * })
   * 
   */
  create<T extends VATRateCreateArgs>(args: Prisma.SelectSubset<T, VATRateCreateArgs<ExtArgs>>): Prisma.Prisma__VATRateClient<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VATRates.
   * @param {VATRateCreateManyArgs} args - Arguments to create many VATRates.
   * @example
   * // Create many VATRates
   * const vATRate = await prisma.vATRate.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VATRateCreateManyArgs>(args?: Prisma.SelectSubset<T, VATRateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VATRates and returns the data saved in the database.
   * @param {VATRateCreateManyAndReturnArgs} args - Arguments to create many VATRates.
   * @example
   * // Create many VATRates
   * const vATRate = await prisma.vATRate.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VATRates and only return the `id`
   * const vATRateWithIdOnly = await prisma.vATRate.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VATRateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VATRateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VATRate.
   * @param {VATRateDeleteArgs} args - Arguments to delete one VATRate.
   * @example
   * // Delete one VATRate
   * const VATRate = await prisma.vATRate.delete({
   *   where: {
   *     // ... filter to delete one VATRate
   *   }
   * })
   * 
   */
  delete<T extends VATRateDeleteArgs>(args: Prisma.SelectSubset<T, VATRateDeleteArgs<ExtArgs>>): Prisma.Prisma__VATRateClient<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VATRate.
   * @param {VATRateUpdateArgs} args - Arguments to update one VATRate.
   * @example
   * // Update one VATRate
   * const vATRate = await prisma.vATRate.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VATRateUpdateArgs>(args: Prisma.SelectSubset<T, VATRateUpdateArgs<ExtArgs>>): Prisma.Prisma__VATRateClient<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VATRates.
   * @param {VATRateDeleteManyArgs} args - Arguments to filter VATRates to delete.
   * @example
   * // Delete a few VATRates
   * const { count } = await prisma.vATRate.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VATRateDeleteManyArgs>(args?: Prisma.SelectSubset<T, VATRateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VATRates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATRateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VATRates
   * const vATRate = await prisma.vATRate.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VATRateUpdateManyArgs>(args: Prisma.SelectSubset<T, VATRateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VATRates and returns the data updated in the database.
   * @param {VATRateUpdateManyAndReturnArgs} args - Arguments to update many VATRates.
   * @example
   * // Update many VATRates
   * const vATRate = await prisma.vATRate.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VATRates and only return the `id`
   * const vATRateWithIdOnly = await prisma.vATRate.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VATRateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VATRateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VATRate.
   * @param {VATRateUpsertArgs} args - Arguments to update or create a VATRate.
   * @example
   * // Update or create a VATRate
   * const vATRate = await prisma.vATRate.upsert({
   *   create: {
   *     // ... data to create a VATRate
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VATRate we want to update
   *   }
   * })
   */
  upsert<T extends VATRateUpsertArgs>(args: Prisma.SelectSubset<T, VATRateUpsertArgs<ExtArgs>>): Prisma.Prisma__VATRateClient<runtime.Types.Result.GetResult<Prisma.$VATRatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VATRates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATRateCountArgs} args - Arguments to filter VATRates to count.
   * @example
   * // Count the number of VATRates
   * const count = await prisma.vATRate.count({
   *   where: {
   *     // ... the filter for the VATRates we want to count
   *   }
   * })
  **/
  count<T extends VATRateCountArgs>(
    args?: Prisma.Subset<T, VATRateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VATRateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VATRate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATRateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VATRateAggregateArgs>(args: Prisma.Subset<T, VATRateAggregateArgs>): Prisma.PrismaPromise<GetVATRateAggregateType<T>>

  /**
   * Group by VATRate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VATRateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VATRateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VATRateGroupByArgs['orderBy'] }
      : { orderBy?: VATRateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VATRateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVATRateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VATRate model
 */
readonly fields: VATRateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VATRate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VATRateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VATRate model
 */
export interface VATRateFieldRefs {
  readonly id: Prisma.FieldRef<"VATRate", 'String'>
  readonly rate: Prisma.FieldRef<"VATRate", 'Float'>
  readonly name: Prisma.FieldRef<"VATRate", 'String'>
  readonly description: Prisma.FieldRef<"VATRate", 'String'>
  readonly active: Prisma.FieldRef<"VATRate", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"VATRate", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"VATRate", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VATRate findUnique
 */
export type VATRateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * Filter, which VATRate to fetch.
   */
  where: Prisma.VATRateWhereUniqueInput
}

/**
 * VATRate findUniqueOrThrow
 */
export type VATRateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * Filter, which VATRate to fetch.
   */
  where: Prisma.VATRateWhereUniqueInput
}

/**
 * VATRate findFirst
 */
export type VATRateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * Filter, which VATRate to fetch.
   */
  where?: Prisma.VATRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VATRates to fetch.
   */
  orderBy?: Prisma.VATRateOrderByWithRelationInput | Prisma.VATRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VATRates.
   */
  cursor?: Prisma.VATRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VATRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VATRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VATRates.
   */
  distinct?: Prisma.VATRateScalarFieldEnum | Prisma.VATRateScalarFieldEnum[]
}

/**
 * VATRate findFirstOrThrow
 */
export type VATRateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * Filter, which VATRate to fetch.
   */
  where?: Prisma.VATRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VATRates to fetch.
   */
  orderBy?: Prisma.VATRateOrderByWithRelationInput | Prisma.VATRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VATRates.
   */
  cursor?: Prisma.VATRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VATRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VATRates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VATRates.
   */
  distinct?: Prisma.VATRateScalarFieldEnum | Prisma.VATRateScalarFieldEnum[]
}

/**
 * VATRate findMany
 */
export type VATRateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * Filter, which VATRates to fetch.
   */
  where?: Prisma.VATRateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VATRates to fetch.
   */
  orderBy?: Prisma.VATRateOrderByWithRelationInput | Prisma.VATRateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VATRates.
   */
  cursor?: Prisma.VATRateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VATRates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VATRates.
   */
  skip?: number
  distinct?: Prisma.VATRateScalarFieldEnum | Prisma.VATRateScalarFieldEnum[]
}

/**
 * VATRate create
 */
export type VATRateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * The data needed to create a VATRate.
   */
  data: Prisma.XOR<Prisma.VATRateCreateInput, Prisma.VATRateUncheckedCreateInput>
}

/**
 * VATRate createMany
 */
export type VATRateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VATRates.
   */
  data: Prisma.VATRateCreateManyInput | Prisma.VATRateCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VATRate createManyAndReturn
 */
export type VATRateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * The data used to create many VATRates.
   */
  data: Prisma.VATRateCreateManyInput | Prisma.VATRateCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VATRate update
 */
export type VATRateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * The data needed to update a VATRate.
   */
  data: Prisma.XOR<Prisma.VATRateUpdateInput, Prisma.VATRateUncheckedUpdateInput>
  /**
   * Choose, which VATRate to update.
   */
  where: Prisma.VATRateWhereUniqueInput
}

/**
 * VATRate updateMany
 */
export type VATRateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VATRates.
   */
  data: Prisma.XOR<Prisma.VATRateUpdateManyMutationInput, Prisma.VATRateUncheckedUpdateManyInput>
  /**
   * Filter which VATRates to update
   */
  where?: Prisma.VATRateWhereInput
  /**
   * Limit how many VATRates to update.
   */
  limit?: number
}

/**
 * VATRate updateManyAndReturn
 */
export type VATRateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * The data used to update VATRates.
   */
  data: Prisma.XOR<Prisma.VATRateUpdateManyMutationInput, Prisma.VATRateUncheckedUpdateManyInput>
  /**
   * Filter which VATRates to update
   */
  where?: Prisma.VATRateWhereInput
  /**
   * Limit how many VATRates to update.
   */
  limit?: number
}

/**
 * VATRate upsert
 */
export type VATRateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * The filter to search for the VATRate to update in case it exists.
   */
  where: Prisma.VATRateWhereUniqueInput
  /**
   * In case the VATRate found by the `where` argument doesn't exist, create a new VATRate with this data.
   */
  create: Prisma.XOR<Prisma.VATRateCreateInput, Prisma.VATRateUncheckedCreateInput>
  /**
   * In case the VATRate was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VATRateUpdateInput, Prisma.VATRateUncheckedUpdateInput>
}

/**
 * VATRate delete
 */
export type VATRateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
  /**
   * Filter which VATRate to delete.
   */
  where: Prisma.VATRateWhereUniqueInput
}

/**
 * VATRate deleteMany
 */
export type VATRateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VATRates to delete
   */
  where?: Prisma.VATRateWhereInput
  /**
   * Limit how many VATRates to delete.
   */
  limit?: number
}

/**
 * VATRate without action
 */
export type VATRateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VATRate
   */
  select?: Prisma.VATRateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VATRate
   */
  omit?: Prisma.VATRateOmit<ExtArgs> | null
}
